# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fingerlickinggoodness12/FreeList-Allocator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fingerlickinggoodness12/FreeList-Allocator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fingerlickinggoodness12/FreeList-Allocator/CMakeFiles /home/fingerlickinggoodness12/FreeList-Allocator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fingerlickinggoodness12/FreeList-Allocator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_arena

# Build rule for target.
test_arena: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_arena
.PHONY : test_arena

# fast build rule for target.
test_arena/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/build
.PHONY : test_arena/fast

#=============================================================================
# Target rules for targets named test_allocator

# Build rule for target.
test_allocator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_allocator
.PHONY : test_allocator

# fast build rule for target.
test_allocator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/build
.PHONY : test_allocator/fast

#=============================================================================
# Target rules for targets named test_logger

# Build rule for target.
test_logger: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_logger
.PHONY : test_logger

# fast build rule for target.
test_logger/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_logger.dir/build.make CMakeFiles/test_logger.dir/build
.PHONY : test_logger/fast

#=============================================================================
# Target rules for targets named test_threads

# Build rule for target.
test_threads: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_threads
.PHONY : test_threads

# fast build rule for target.
test_threads/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_threads.dir/build.make CMakeFiles/test_threads.dir/build
.PHONY : test_threads/fast

allocator/allocator.o: allocator/allocator.c.o
.PHONY : allocator/allocator.o

# target to build an object file
allocator/allocator.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/allocator/allocator.c.o
.PHONY : allocator/allocator.c.o

allocator/allocator.i: allocator/allocator.c.i
.PHONY : allocator/allocator.i

# target to preprocess a source file
allocator/allocator.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/allocator/allocator.c.i
.PHONY : allocator/allocator.c.i

allocator/allocator.s: allocator/allocator.c.s
.PHONY : allocator/allocator.s

# target to generate assembly for a file
allocator/allocator.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/allocator/allocator.c.s
.PHONY : allocator/allocator.c.s

arena/arena.o: arena/arena.c.o
.PHONY : arena/arena.o

# target to build an object file
arena/arena.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/arena/arena.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/arena/arena.c.o
.PHONY : arena/arena.c.o

arena/arena.i: arena/arena.c.i
.PHONY : arena/arena.i

# target to preprocess a source file
arena/arena.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/arena/arena.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/arena/arena.c.i
.PHONY : arena/arena.c.i

arena/arena.s: arena/arena.c.s
.PHONY : arena/arena.s

# target to generate assembly for a file
arena/arena.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/arena/arena.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/arena/arena.c.s
.PHONY : arena/arena.c.s

bitmap/bitmap.o: bitmap/bitmap.c.o
.PHONY : bitmap/bitmap.o

# target to build an object file
bitmap/bitmap.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/bitmap/bitmap.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/bitmap/bitmap.c.o
.PHONY : bitmap/bitmap.c.o

bitmap/bitmap.i: bitmap/bitmap.c.i
.PHONY : bitmap/bitmap.i

# target to preprocess a source file
bitmap/bitmap.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/bitmap/bitmap.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/bitmap/bitmap.c.i
.PHONY : bitmap/bitmap.c.i

bitmap/bitmap.s: bitmap/bitmap.c.s
.PHONY : bitmap/bitmap.s

# target to generate assembly for a file
bitmap/bitmap.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/bitmap/bitmap.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/bitmap/bitmap.c.s
.PHONY : bitmap/bitmap.c.s

hash_table/hash_table.o: hash_table/hash_table.c.o
.PHONY : hash_table/hash_table.o

# target to build an object file
hash_table/hash_table.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/hash_table/hash_table.c.o
.PHONY : hash_table/hash_table.c.o

hash_table/hash_table.i: hash_table/hash_table.c.i
.PHONY : hash_table/hash_table.i

# target to preprocess a source file
hash_table/hash_table.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/hash_table/hash_table.c.i
.PHONY : hash_table/hash_table.c.i

hash_table/hash_table.s: hash_table/hash_table.c.s
.PHONY : hash_table/hash_table.s

# target to generate assembly for a file
hash_table/hash_table.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/hash_table/hash_table.c.s
.PHONY : hash_table/hash_table.c.s

logger/buffer.o: logger/buffer.c.o
.PHONY : logger/buffer.o

# target to build an object file
logger/buffer.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/logger/buffer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/logger/buffer.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_logger.dir/build.make CMakeFiles/test_logger.dir/logger/buffer.c.o
.PHONY : logger/buffer.c.o

logger/buffer.i: logger/buffer.c.i
.PHONY : logger/buffer.i

# target to preprocess a source file
logger/buffer.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/logger/buffer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/logger/buffer.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_logger.dir/build.make CMakeFiles/test_logger.dir/logger/buffer.c.i
.PHONY : logger/buffer.c.i

logger/buffer.s: logger/buffer.c.s
.PHONY : logger/buffer.s

# target to generate assembly for a file
logger/buffer.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/logger/buffer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/logger/buffer.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_logger.dir/build.make CMakeFiles/test_logger.dir/logger/buffer.c.s
.PHONY : logger/buffer.c.s

logger/logger.o: logger/logger.c.o
.PHONY : logger/logger.o

# target to build an object file
logger/logger.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/logger/logger.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_logger.dir/build.make CMakeFiles/test_logger.dir/logger/logger.c.o
.PHONY : logger/logger.c.o

logger/logger.i: logger/logger.c.i
.PHONY : logger/logger.i

# target to preprocess a source file
logger/logger.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/logger/logger.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_logger.dir/build.make CMakeFiles/test_logger.dir/logger/logger.c.i
.PHONY : logger/logger.c.i

logger/logger.s: logger/logger.c.s
.PHONY : logger/logger.s

# target to generate assembly for a file
logger/logger.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/logger/logger.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_logger.dir/build.make CMakeFiles/test_logger.dir/logger/logger.c.s
.PHONY : logger/logger.c.s

tests/allocator_test.o: tests/allocator_test.c.o
.PHONY : tests/allocator_test.o

# target to build an object file
tests/allocator_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/tests/allocator_test.c.o
.PHONY : tests/allocator_test.c.o

tests/allocator_test.i: tests/allocator_test.c.i
.PHONY : tests/allocator_test.i

# target to preprocess a source file
tests/allocator_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/tests/allocator_test.c.i
.PHONY : tests/allocator_test.c.i

tests/allocator_test.s: tests/allocator_test.c.s
.PHONY : tests/allocator_test.s

# target to generate assembly for a file
tests/allocator_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/tests/allocator_test.c.s
.PHONY : tests/allocator_test.c.s

tests/arena_test.o: tests/arena_test.c.o
.PHONY : tests/arena_test.o

# target to build an object file
tests/arena_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/tests/arena_test.c.o
.PHONY : tests/arena_test.c.o

tests/arena_test.i: tests/arena_test.c.i
.PHONY : tests/arena_test.i

# target to preprocess a source file
tests/arena_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/tests/arena_test.c.i
.PHONY : tests/arena_test.c.i

tests/arena_test.s: tests/arena_test.c.s
.PHONY : tests/arena_test.s

# target to generate assembly for a file
tests/arena_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/tests/arena_test.c.s
.PHONY : tests/arena_test.c.s

tests/logger_test.o: tests/logger_test.c.o
.PHONY : tests/logger_test.o

# target to build an object file
tests/logger_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_logger.dir/build.make CMakeFiles/test_logger.dir/tests/logger_test.c.o
.PHONY : tests/logger_test.c.o

tests/logger_test.i: tests/logger_test.c.i
.PHONY : tests/logger_test.i

# target to preprocess a source file
tests/logger_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_logger.dir/build.make CMakeFiles/test_logger.dir/tests/logger_test.c.i
.PHONY : tests/logger_test.c.i

tests/logger_test.s: tests/logger_test.c.s
.PHONY : tests/logger_test.s

# target to generate assembly for a file
tests/logger_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_logger.dir/build.make CMakeFiles/test_logger.dir/tests/logger_test.c.s
.PHONY : tests/logger_test.c.s

tests/multithreading_test.o: tests/multithreading_test.c.o
.PHONY : tests/multithreading_test.o

# target to build an object file
tests/multithreading_test.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_threads.dir/build.make CMakeFiles/test_threads.dir/tests/multithreading_test.c.o
.PHONY : tests/multithreading_test.c.o

tests/multithreading_test.i: tests/multithreading_test.c.i
.PHONY : tests/multithreading_test.i

# target to preprocess a source file
tests/multithreading_test.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_threads.dir/build.make CMakeFiles/test_threads.dir/tests/multithreading_test.c.i
.PHONY : tests/multithreading_test.c.i

tests/multithreading_test.s: tests/multithreading_test.c.s
.PHONY : tests/multithreading_test.s

# target to generate assembly for a file
tests/multithreading_test.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_threads.dir/build.make CMakeFiles/test_threads.dir/tests/multithreading_test.c.s
.PHONY : tests/multithreading_test.c.s

threads/threads.o: threads/threads.c.o
.PHONY : threads/threads.o

# target to build an object file
threads/threads.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/threads/threads.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/threads/threads.c.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_threads.dir/build.make CMakeFiles/test_threads.dir/threads/threads.c.o
.PHONY : threads/threads.c.o

threads/threads.i: threads/threads.c.i
.PHONY : threads/threads.i

# target to preprocess a source file
threads/threads.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/threads/threads.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/threads/threads.c.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_threads.dir/build.make CMakeFiles/test_threads.dir/threads/threads.c.i
.PHONY : threads/threads.c.i

threads/threads.s: threads/threads.c.s
.PHONY : threads/threads.s

# target to generate assembly for a file
threads/threads.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_arena.dir/build.make CMakeFiles/test_arena.dir/threads/threads.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_allocator.dir/build.make CMakeFiles/test_allocator.dir/threads/threads.c.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_threads.dir/build.make CMakeFiles/test_threads.dir/threads/threads.c.s
.PHONY : threads/threads.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test_allocator"
	@echo "... test_arena"
	@echo "... test_logger"
	@echo "... test_threads"
	@echo "... allocator/allocator.o"
	@echo "... allocator/allocator.i"
	@echo "... allocator/allocator.s"
	@echo "... arena/arena.o"
	@echo "... arena/arena.i"
	@echo "... arena/arena.s"
	@echo "... bitmap/bitmap.o"
	@echo "... bitmap/bitmap.i"
	@echo "... bitmap/bitmap.s"
	@echo "... hash_table/hash_table.o"
	@echo "... hash_table/hash_table.i"
	@echo "... hash_table/hash_table.s"
	@echo "... logger/buffer.o"
	@echo "... logger/buffer.i"
	@echo "... logger/buffer.s"
	@echo "... logger/logger.o"
	@echo "... logger/logger.i"
	@echo "... logger/logger.s"
	@echo "... tests/allocator_test.o"
	@echo "... tests/allocator_test.i"
	@echo "... tests/allocator_test.s"
	@echo "... tests/arena_test.o"
	@echo "... tests/arena_test.i"
	@echo "... tests/arena_test.s"
	@echo "... tests/logger_test.o"
	@echo "... tests/logger_test.i"
	@echo "... tests/logger_test.s"
	@echo "... tests/multithreading_test.o"
	@echo "... tests/multithreading_test.i"
	@echo "... tests/multithreading_test.s"
	@echo "... threads/threads.o"
	@echo "... threads/threads.i"
	@echo "... threads/threads.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

