#include "allocator.h"
#include <pthread.h>
#include <stdalign.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <stdnoreturn.h>
#include <string.h>
#include <stdlib.h>
#include <sys/mman.h>
#include <sys/types.h>

/*
#include "allocator.h"
#include <stdalign.h>
#include <string.h>
#include <stdlib.h>
#include <sys/types.h>
*/
typedef struct byte_entries_t {
    void* ptr;
    struct offset_entries_t* offset;
    struct byte_entries_t* next;
    unsigned int bytes;
    unsigned char inuse;
} byte_entries_t;

typedef struct offset_entries_t {
    void* ptr;
    struct byte_entries_t* bytes;
    struct offset_entries_t* next;
    unsigned int offset;
    unsigned char inuse;
} offset_entries_t;

typedef struct entry_table_t {
    byte_entries_t** entries;
    unsigned int bucket_count;  /* always a power of two */
} entry_table_t;


/////////////////////////
// ENTRY TABLE SECTION //
////////////////////////


FORCE_INLINE void entry_table_init(entry_table_t* table) {
    table->entries = mmap(NULL, 64 * sizeof(byte_entries_t*), PROT_WRITE | PROT_READ, MAP_SHARED | MAP_ANONYMOUS | MAP_NORESERVE, -1, 0);
    if (table->entries == MAP_FAILED) return;
    memset(table->entries, 0, sizeof(byte_entries_t*) * 64);
    table->bucket_count = 64;
    return;
}

/**
    * @description: Resizes the data member field copying over the old data to the new memory block.
    * @param table: A stack allocated addres variable 
    * @note: It resizes itself by the multiple of a numerical value that's a power of 2 i.e 64
    * @return: Nothing
*/
FORCE_INLINE void resize_table(entry_table_t* table) {
    unsigned int new_bucket_count = table->bucket_count * 2;
    byte_entries_t** new_entries =  shared_address(NULL, new_bucket_count * sizeof(byte_entries_t*), PROT_WRITE | PROT_READ, MAP_SHARED | MAP_ANONYMOUS | MAP_NORESERVE, -1, 0);
    if (new_entries == MAP_FAILED) return;
    int res = madvise(new_entries, new_bucket_count * sizeof(byte_entries_t*), MADV_SEQUENTIAL | MADV_MERGEABLE);
    if (res == -1) {
        munmap_address(new_entries, sizeof(byte_entries_t*) * new_bucket_count);
        return;
    }
    memcpy(new_entries, table->entries, sizeof(byte_entries_t*) * table->bucket_count);
    munmap_address(table->entries, sizeof(byte_entries_t*) * table->bucket_count);
    table->entries = new_entries;
    table->bucket_count = new_bucket_count;
}

FORCE_INLINE byte_entries_t* create_byte_entry(const unsigned int bytes, const unsigned char inuse, void* ptr) {
    byte_entries_t* bnode = aligned_alloc(alignof(byte_entries_t), sizeof(byte_entries_t));
    if (bnode) {
        memset(bnode, 0, sizeof(byte_entries_t)); 
        bnode->ptr = ptr; 
        bnode->offset = NULL; 
        bnode->next = NULL; 
        bnode->bytes = bytes; 
        bnode->inuse = inuse;
        return bnode;
    }
    return NULL;
}

FORCE_INLINE offset_entries_t* create_offset_entry(const unsigned int offset, const unsigned char inuse, void* ptr) {
    offset_entries_t* onode = aligned_alloc(alignof(offset_entries_t), sizeof(offset_entries_t));
    if (onode) {
        memset(onode, 0, sizeof(offset_entries_t)); 
        onode->ptr = ptr; 
        onode->bytes = NULL; 
        onode->next = NULL; 
        onode->offset = offset; 
        onode->inuse = inuse;
        return onode;
    }
    return NULL;
}

/**
    * @description: Free function that adds a new bijection pair, and adds the existing entries to the back.
    * @param table: A stack address variable apart of the bucket_t
    * @param idx: A variable that has been already pre-computed by the allocator's bitmap functions or a bucket function
    * @param offset: An offset generated by the arena 
    * @param bytes: The requested bytes 
    * @param inuse: Mark the entry as 0x0 not in use or 0x01 as in use 
    * @return: Return's nothing
*/
FORCE_INLINE void set(entry_table_t* table, const unsigned int idx, const unsigned int offset, const unsigned int bytes, const unsigned char inuse, void* ptr) {
    if (!table->entries) entry_table_init(table);
    else if (idx >= table->bucket_count) resize_table(table);

    byte_entries_t* bnode = create_byte_entry(bytes, inuse, ptr);
    offset_entries_t* onode = create_offset_entry(offset, inuse, ptr);
    if (!bnode || !onode) { free(bnode); free(onode); return; }

    bnode->offset = onode;
    onode->bytes = bnode;

    bnode->next = table->entries[idx];
    table->entries[idx] = bnode;
}

FORCE_INLINE byte_entries_t* get_entry_t_by_bytes(entry_table_t* table, const int idx, const unsigned int bytes, const unsigned char inuse) {
    byte_entries_t* n = NULL;
    if (table->entries) n = table->entries[idx];
    if (bytes != 0) { 
        while (__builtin_expect(n != NULL, 1)) {
            __builtin_prefetch(n->next, 0, 1);
            unsigned int matches = (n->bytes == bytes) & (n->inuse == inuse);
            if (matches) return n;
            n = n->next;
        }
    }
    else {
        while (__builtin_expect(n != NULL, 1)) {
            __builtin_prefetch(n->next, 0, 1);
            if (n->inuse) return n;
            n = n->next;
        }
    }
    return NULL;
}

FORCE_INLINE offset_entries_t* get_entry_t_by_offset(entry_table_t* table, const int idx, const unsigned int offset, const unsigned char inuse) {
    byte_entries_t* bnode = NULL;
    if (table->entries) bnode = table->entries[idx];
    while (__builtin_expect(bnode != NULL, 1)) {
        __builtin_prefetch(bnode->next, 0, 1);
        offset_entries_t* onode = bnode->offset;
        if (onode->offset == offset && onode->inuse == inuse) return onode;
        bnode = bnode->next;
    }
    return NULL;
}

/**
    * @description: Free function that updates a bijection nodes
    * @param table: A stack address variable apart of the bucket_t
    * @param idx: A variable that has been already pre-computed by the allocator's bitmap functions or a bucket function
    * @param offset: An offset generated by the arena 
    * @param bytes: The requested bytes 
    * @param inuse: Mark the entry as 0x0 not in use or 0x01 as in use 
    * @return: Return's nothing
*/
FORCE_INLINE void update(entry_table_t* table, const int idx, const unsigned int offset, const unsigned int bytes, const unsigned char inuse) {
    if (!table->entries) return;
    if ((offset == 0) && (bytes == 0)) return;

    byte_entries_t* bnode = table->entries[idx];
    while (bnode) {
        int matches = (offset != 0) ? (bnode->offset->offset == offset) : (bnode->bytes == bytes);
        if (matches) {
            bnode->inuse = inuse;
            bnode->offset->inuse = inuse;
            break;
        }
        bnode = bnode->next;
    }
}

/**
    * @description: Free function that destroys a bijection node
    * @param table: A stack address allocated variable apart of the bucket_t
    * @param idx: A variable that has been already pre-computed by the allocator's bitmap functions or a bucket function
    * @param offset: An offset generated by the arena 
    * @param bytes: The requested bytes 
    * @param inuse: Mark the entry as 0x0 not in use or 0x01 as in use 
    * @return: Return's nothing
*/
FORCE_INLINE void destroy(entry_table_t* table, const int idx, const unsigned int offset, const unsigned int bytes) {
    if (!table->entries) return;
    if ((offset == 0) && (bytes == 0)) return;

    byte_entries_t* prev = NULL;
    byte_entries_t* cur = table->entries[idx];
    byte_entries_t* bn = NULL;

    while (cur) {
        int matches = (offset != 0) ? (cur->offset->offset == offset) : (cur->bytes == bytes);
        if (matches) { bn = cur; break; }
        prev = cur;
        cur = cur->next;
    }
    if (!bn) return;

    if (prev) prev->next = bn->next; else table->entries[idx] = bn->next;

    offset_entries_t* on = bn->offset;

    memset(bn, 0, offsetof(byte_entries_t, next));
    memset((char*)bn + offsetof(byte_entries_t, next) + sizeof(byte_entries_t*), 0,
           sizeof(byte_entries_t) - offsetof(byte_entries_t, next) - sizeof(byte_entries_t*));
    free(bn);

    if (on) {
        memset(on, 0, offsetof(offset_entries_t, next));
        memset((char*)on + offsetof(offset_entries_t, next) + sizeof(offset_entries_t*), 0,
               sizeof(offset_entries_t) - offsetof(offset_entries_t, next) - sizeof(offset_entries_t*));
        free(on);
    }
}

FORCE_INLINE void clean(entry_table_t *table) {
    if (!table) return;
    if (table->entries) {
        for (unsigned int i = 0; i < table->bucket_count; i++) {
            byte_entries_t* n = table->entries[i];
            while (n && n->ptr) {
                byte_entries_t* next = n->next;
                offset_entries_t* on = n->offset; /* bijected pair -- must free both halves; no separate map does this anymore */

                memset(n, 0, sizeof(byte_entries_t));
                free(n);

                if (on) {
                    memset(on, 0, sizeof(offset_entries_t));
                    free(on);
                }
                n = next;
            }
        }
        munmap_address(table->entries, sizeof(byte_entries_t*) * table->bucket_count);
    }
    memset(table, 0, sizeof(entry_table_t));
}

FORCE_INLINE void debug_entry_table_t(const unsigned char mode, entry_table_t* table, const int idx) {
    if (mode == 0x0) {
        byte_entries_t* bn = table->entries[idx];
        while (bn->next != NULL) {
            if (bn->offset->offset) {
                printf("Offset value is: %d\n", bn->offset->offset);
                printf("Inuse Value is: %#0x\n", bn->offset->offset);
            }
            bn = bn->next;
        }
    }
    else if (mode == 0x01) {
        byte_entries_t* n = table->entries[idx];
        while (n->next != NULL) {
            printf("Offset value is: %d\n", n->bytes);
            n = n->next;
        }
    }
}
// coalescing is when you take freed adjacent memory blocks and combine them together to form a size specific to the user's request
typedef struct blocks_t {
    struct blocks_t** chain;
    struct blocks_t* next;
    entry_table_t*   table; /* link bucket_t->table to this field */
    void*            ptr;
    unsigned int     bytes;
    unsigned int     offset;
    unsigned int     size;
    unsigned char    inuse;
} blocks_t;

/////////////////////////
// BLOCK CHAIN SECTION //
////////////////////////

FORCE_INLINE void init_blocks_t(blocks_t* blocks) {
    blocks->size = 64;
    blocks->chain = shared_address(NULL, blocks->size * sizeof(blocks_t*), PROT_WRITE | PROT_READ, MAP_SHARED | MAP_ANONYMOUS | MAP_NORESERVE, -1, 0);
    if (blocks->chain == MAP_FAILED) return;
    int res = madvise(blocks->chain, blocks->size * sizeof(blocks_t*), MADV_SEQUENTIAL | MADV_MERGEABLE);
    if (res == -1) return;
    memset(blocks->chain, 0, blocks->size * sizeof(blocks_t));
    return;
}

FORCE_INLINE blocks_t* create_block_t() {
    blocks_t* block = aligned_alloc(alignof(blocks_t), sizeof(blocks_t));
    if (!block) return NULL;
    memset(block, 0, sizeof(blocks_t));
    return block;
}

FORCE_INLINE void resize_blocks(blocks_t* blocks) {
    const unsigned int new_size = blocks->size * 2;
    blocks_t** chain = shared_address(NULL, new_size * sizeof(blocks_t*), PROT_WRITE | PROT_READ, MAP_SHARED | MAP_ANONYMOUS | MAP_NORESERVE, -1, 0);
    if (chain == MAP_FAILED) return;
    int res = madvise(chain, new_size * sizeof(blocks_t*), MADV_SEQUENTIAL | MADV_MERGEABLE);
    if (res == -1) return;
    memcpy(chain, blocks->chain, sizeof(blocks_t) * blocks->size);
    munmap_address(blocks->chain, sizeof(blocks_t) * blocks->size);
    blocks->chain = chain;
    blocks->size = new_size;
    return;
}

// We need to merge the arena's offsets together and add the bytes together to get the specific fit 
// But when we do merge the offsets together, we also need to merge the pointers together i.e using the OR logic gate
// We also have to be careful of not overflowing, hence the leftover. If we do overflow then we need to get the leftover bytes
// and add the offset to the bnode->ptr
FORCE_INLINE void merge(blocks_t* blocks, entry_table_t* table, const unsigned int idx, const unsigned int bytes) {
    if (!blocks->chain) init_blocks_t(blocks);
    if (blocks->size < idx) resize_blocks(blocks);
    else if (!blocks->chain[idx]) blocks->chain[idx] = create_block_t();
    
    unsigned int total = 0;
    if (!blocks->chain[idx]) return;
    else if (blocks->chain[idx]->inuse == 0x0) {
        if (!blocks->table) blocks->table = table;
        while (total != bytes) {
            byte_entries_t* bnode = get_entry_t_by_bytes(table, idx, 0, 0x0);
            if (!bnode) break;
            unsigned int accumalting_bytes = blocks->chain[idx]->bytes += bnode->bytes;
            if (accumalting_bytes - total > 0) {
                unsigned int leftover = accumalting_bytes - total;
                bnode->offset->offset -= blocks->chain[idx]->offset;
                bnode->bytes = leftover;
                break;
            }
            if (!blocks->chain[idx]->ptr) blocks->chain[idx]->ptr = bnode->ptr;
            else {
                uintptr_t a = (uintptr_t)blocks->chain[idx]->ptr, b = (uintptr_t)bnode->ptr;
                blocks->chain[idx]->ptr = (void*)(a | b);
            } 
            blocks->chain[idx]->bytes += bnode->bytes;
            blocks->chain[idx]->offset += bnode->offset->offset;
            destroy(blocks->table, idx, bnode->offset->offset, bnode->bytes);
            bnode = bnode->next;
        }
        return;
    }
    blocks_t* block = create_block_t();
    block->next = blocks->chain[idx];
    blocks->chain[idx] = block;
    return merge(blocks, blocks->table, idx, bytes);
}

FORCE_INLINE blocks_t* get_block_entry(blocks_t* blocks, const unsigned int idx, const unsigned int bytes) {
    if (bytes != 0) {}
    blocks_t* block = blocks->chain[idx];
    return block;
}

FORCE_INLINE blocks_t* update_blocks(blocks_t* blocks, const unsigned int idx, const unsigned int bytes) {
    if (bytes != 0) {}
    blocks_t* block = blocks->chain[idx];
    return block;
}

typedef struct bucket_t {
    blocks_t       blocks;
    entry_table_t  table;
    arena_t*       arena;
    unsigned char  flag;
} bucket_t;
FORCE_INLINE int find_bucket_index(bucket_t* slot);


/////////////////////
// BUCKET SECTION //
///////////////////


/**
    * @description: A Free function that finds a free slot based on the size at O(n). 
    * @param sz: can be a numeric value of size: 64, 128, or 256. 
    * @return: Returns a slot right after checking the bucket's bitmap.
    * @note: if nothing is returned, that means all of the slots from small, medium and large are occupied. 
*/
FORCE_INLINE bucket_t* find_free_slot(size_t sz) {
    int idx = -1;
    if (sz < 1) return NULL;
    else if (sz <= BUCKET_SMALL_CAP) {
        idx = allocator.bitmap.bitmap_test(allocator.bitmap, 0, BUCKET_SMALL_CAP - 1);
        #if LOGGING == 1
            #if LOGLEVEL == 0  
                printf("[find_free_slot] small idx: %d\n", idx);
            #elif LOGLEVEL > 1
                // TODO: Include the logger variable here and its functions
            #endif
        #endif
        if (idx != -1) return &allocator.bucket.small[idx];
    }
    else if (sz <= BUCKET_MEDIUM_CAP) {
        idx = allocator.bitmap.bitmap_test(allocator.bitmap, 0, BUCKET_MEDIUM_CAP - 1);
        #if LOGGING == 1
            #if LOGLEVEL == 0 
                printf("[find_free_slot] medium idx: %d\n", idx);
            #elif LOGLEVEL > 1
                // TODO: Include the logger variable here and its functions
            #endif
        #endif 
        if (idx != -1) return &allocator.bucket.medium[idx];
    }
    else if (sz <= BUCKET_LARGE_CAP) {
        idx = allocator.bitmap.bitmap_test(allocator.bitmap, 0, BUCKET_LARGE_CAP - 1);
        #if LOGGING == 1
            #if LOGLEVEL == 0 
                printf("[find_free_slot] large idx: %d\n", idx);
            #elif LOGLEVEL > 1
                // TODO: Include the logger variable here and its functions
            #endif
        #endif 
        if (idx != -1) return &allocator.bucket.large[idx];
    }
    else {
        // coalescing feature goes here...
    }
    return NULL;
}

/**
    * @description: A Free function that finds the specific bucket, which contains an arena that the memory address came from or not.
    * @param ptr: A memory address that came from the arena. 
    * @return: Returns null if nothing was found.
    * @note: If nothing was found, that means the 'ptr' memory address is from a memory address that is not associated with the arena. 
             Or an address that was allocated on the heap. 
*/
FORCE_INLINE bucket_t* find_slot(void* ptr) {
    uintptr_t p = (uintptr_t)ptr;

    for (unsigned int i = 0; i < BUCKET_SMALL_CAP; i++) {
        bucket_t* b = &allocator.bucket.small[i];
        if (b->arena && p >= (uintptr_t)b->arena->chunk && p < (uintptr_t)b->arena->chunk + ARENA_SIZE) {
            unsigned int offset = (unsigned int)(p - (uintptr_t)b->arena->chunk);
            if (get_entry_t_by_offset(&b->table, i, offset, 0x01)) {
                if (b->flag == 0x01 && b->arena->flag == 0x01) {
                    b->flag = 0x0; b->arena->flag = 0x0;
                    allocator.bitmap = allocator.bitmap.bitmap_clear(allocator.bitmap, i, 0, BUCKET_SMALL_CAP - 1);
                }
                return b;
            }
        }
    }
    for (unsigned int i = 0; i < BUCKET_MEDIUM_CAP; i++) {
        bucket_t* b = &allocator.bucket.medium[i];
        if (b->arena && p >= (uintptr_t)b->arena->chunk && p < (uintptr_t)b->arena->chunk + ARENA_SIZE) {
            unsigned int offset = (unsigned int)(p - (uintptr_t)b->arena->chunk);
            if (get_entry_t_by_offset(&b->table, i, offset, 0x01)) {
                if (b->flag == 0x01 && b->arena->flag == 0x01) {
                    b->flag = 0x0; b->arena->flag = 0x0;
                    allocator.bitmap = allocator.bitmap.bitmap_clear(allocator.bitmap, i, 0, BUCKET_MEDIUM_CAP - 1);
                }
                return b;
            }
        }
    }
    for (unsigned int i = 0; i < BUCKET_LARGE_CAP; i++) {
        bucket_t* b = &allocator.bucket.large[i];
        if (b->arena && p >= (uintptr_t)b->arena->chunk && p < (uintptr_t)b->arena->chunk + ARENA_SIZE) {
            unsigned int offset = (unsigned int)(p - (uintptr_t)b->arena->chunk);
            if (get_entry_t_by_offset(&b->table, i, offset, 0x01)) {
                if (b->flag == 0x01 && b->arena->flag == 0x01) {
                    b->flag = 0x0; b->arena->flag = 0x0;
                    allocator.bitmap = allocator.bitmap.bitmap_clear(allocator.bitmap, i, 0, BUCKET_LARGE_CAP - 1);
                }
                return b;
            }
        }
    }
    return NULL;
}

FORCE_INLINE int find_bucket_index(bucket_t* slot) {
    if (!slot) return -1;
    if (slot >= allocator.bucket.small && slot < allocator.bucket.small + BUCKET_SMALL_CAP) return (int)(slot - allocator.bucket.small);
    if (slot >= allocator.bucket.medium && slot < allocator.bucket.medium + BUCKET_MEDIUM_CAP) return (int)(slot - allocator.bucket.medium);
    if (slot >= allocator.bucket.large && slot < allocator.bucket.large + BUCKET_LARGE_CAP) return (int)(slot - allocator.bucket.large);
    return -1;
}

/**
    * @description: Function that returns the size where it came from 
    * @param slot: Pointer variable that possibly comes from one of the bucket's memory regions
    * @return: Returns either BUCKET_SMALL_CAP, BUCKET_MEDIUM_CAP, or BUCKET_LARGE_CAP, or returns 0
*/
FORCE_INLINE size_t find_bucket_size(const bucket_t* slot) {
    uintptr_t addr = (uintptr_t)slot;
    uintptr_t small_start  = (uintptr_t)allocator.bucket.small;
    uintptr_t small_end    = small_start  + BUCKET_SMALL_CAP  * sizeof(bucket_t);
    uintptr_t medium_start = (uintptr_t)allocator.bucket.medium;
    uintptr_t medium_end   = medium_start + BUCKET_MEDIUM_CAP * sizeof(bucket_t);
    
    if (addr >= small_start && addr < small_end)   return BUCKET_SMALL_CAP;
    if (addr >= medium_start && addr < medium_end) return BUCKET_MEDIUM_CAP;

    uintptr_t large_start = (uintptr_t)allocator.bucket.large;
    uintptr_t large_end   = large_start + BUCKET_LARGE_CAP * sizeof(bucket_t);
    if (addr >= large_start && addr < large_end) return BUCKET_LARGE_CAP;
    return 0;
}

/**
    * @description: A Free Function that pushes the unused memory addresses to bucket.
        It is used with deallocation function
    * @param b: A specific bucket that will now have been updated 
*/
FORCE_INLINE void push_to_bucket(bucket_t* slot, size_t offset) {
    update(&slot->table, find_bucket_index(slot), offset, 0, 0x0);
    return;
}

/**
    * @description: A free function that pops off a memory address that is not in use based on the requested size
    * @param slot: The slot which is bucket_t that has memory addresses to be used. 
    * @param bytes: the requested bytes 
    * @return: Returns null if bucket field is null or if bucket == slot->arena->chunk  
*/
FORCE_INLINE void* pop_from_bucket(bucket_t* slot, size_t bytes) {
    byte_entries_t* tmp = get_entry_t_by_bytes(&slot->table, find_bucket_index(slot),  bytes, 0x0);
    if (!tmp || tmp->ptr == NULL) return NULL;
    void* address = NULL;
    if (tmp) {
        update(&slot->table, find_bucket_index(slot), tmp->offset->offset, 0, 0x01);
        //slot->arena = push(slot->arena, bytes);
        address = tmp->ptr;
    }
    /*#if LOGGING == 0 || LOGGING == 1
        const int line = __LINE__;
        char* res = write_long_cstr(0x01, 1, "Entry variable is: [ %p ]\n", tmp);
        #if LOGGING == 0
            printer.add(0, __FILE__, line, res);
            printer.print(__FILE__, line);
        #else
            logger.add(0, __FILE__, line, res);
        #endif
        cstr_size(1, res) < ALLOC_THRESHOLD ? reset_and_free_cstr(1, res) : unmap_cstr(1, res);
    #endif*/
    return address;
}

[[gnu::cold]]
FORCE_INLINE void bucket_t_dctor() {
    unsigned int small = 0;
    unsigned int medium = 0;
    while (small < BUCKET_SMALL_CAP) {
        arena_t* arena = allocator.bucket.small[small].arena;
        bucket_t slot = allocator.bucket.small[small];
        if (slot.table.entries) clean(&slot.table);
        if (arena) {
            if (arena->chunk) munmap_address(arena->chunk, ARENA_SIZE + 1);
            munmap_address(arena, sizeof(arena_t));
        }
        small = small + 1;
    }
    munmap_address(allocator.bucket.small, BUCKET_SMALL_CAP * sizeof(bucket_t));
    while (medium < BUCKET_MEDIUM_CAP) {
        //arena_t* arena = allocator.bucket.medium[medium].arena;
        bucket_t slot = allocator.bucket.medium[medium];
        if (slot.table.entries) clean(&slot.table);
        /*if (arena != NULL) {
            if (arena->chunk) munmap_address(arena->chunk, ARENA_SIZE + 1);
            munmap_address(arena, sizeof(arena_t));
        }*/
        medium = medium + 1;
    }
    munmap_address(allocator.bucket.medium, BUCKET_MEDIUM_CAP * sizeof(bucket_t));
    unsigned int large = 0;
    while (large < BUCKET_LARGE_CAP) {
        arena_t* arena = allocator.bucket.large[large].arena;
        bucket_t slot = allocator.bucket.large[large];
        if (slot.table.entries) clean(&slot.table);
        if (arena) {
            if (arena->chunk) munmap_address(arena->chunk, ARENA_SIZE + 1);
            munmap_address(arena, sizeof(arena_t));
        }
        large = large + 1;
    }
    munmap_address(allocator.bucket.large, BUCKET_LARGE_CAP * sizeof(bucket_t));
}

/**
    * @description: A Free function that rewinds the arena back to a safe spot, based on certain conditions. 
    * @param slot: A raw pointer that has been allocated on the heap that is apart of the allocator.bucket
    * @note: It will rewind all the way to the very last entry, and if that entry is not inuse, it will destroy the whole entry_table_t chain.
    * @return Nothing
*/
FORCE_INLINE void __rewind(bucket_t* slot) {
    int idx = find_bucket_index(slot);
    byte_entries_t* bnode = slot->table.entries[idx];
    while (bnode && bnode->offset->inuse == 0x0) {
        byte_entries_t* next = bnode->next;
        unsigned int offset = bnode->offset->offset;
        if (next) slot->arena = pop(slot->arena, next->offset->offset);
        destroy(&slot->table, idx, offset, 0);
        bnode = next;
    }
    if (!bnode) clear_arena_t(slot->arena);
}

////////////////////////
// THREADING SECTION //
//////////////////////

FORCE_INLINE void* thread_rewind(struct function_t* meta) {
    void** arguments = routine_metadata_arguments(meta);
    threads_t* st = (threads_t*)arguments[0];
    bucket_t* slot = (bucket_t*)arguments[1];
    int rc = pthread_mutex_lock(&st->lock.mutex);
    if (rc == 0) {
        __rewind(slot);
        st->flag = 0x0;
        pthread_mutex_unlock(&st->lock.mutex);
        join_thread(*st, NULL);
    }
    pthread_exit(NULL);
}

FORCE_INLINE void* thread_update_thread_pool(struct function_t* meta) {
    void** arguments = routine_metadata_arguments(meta);
    threads_t* st = (threads_t*)arguments[0];
    int rc = pthread_mutex_lock(&st->lock.mutex);
    if (rc == 0) {
        update_thread_pool(st, ALLOC_THREAD_POOL_SIZE);
        st->flag = 0x0;
        pthread_mutex_unlock(&st->lock.mutex);
    }
    pthread_exit(NULL);
}

FORCE_INLINE void* thread_create_thread_pool(struct function_t* meta) {
    void** arguments = routine_metadata_arguments(meta);
    threads_t* st = (threads_t*)arguments[0];
    const unsigned int* size = (const unsigned int*)arguments[2];
    const unsigned char* mode = (const unsigned char*)arguments[3];
    int rc = pthread_mutex_lock(&st->lock.mutex);
    if (rc == 0) {
        // pass in allocator.pool as argument[1]
        create_thread_pool((threads_t*)arguments[1], *size, *mode);
        st->flag = 0x0;
        pthread_mutex_unlock(&st->lock.mutex);
    }
    pthread_exit(NULL);
}


////////////////////////
// ALLOCATOR SECTION //
//////////////////////
allocator_t allocator = {0};

[[gnu::hot]]
// TODO: Need to make sure that MADV_MERGEABLE enabled does not consume a lot of processing power; use with care.
FORCE_INLINE void alloc_init(void) {
    int res = 0;
    if (!allocator.bucket.small) {
        allocator.bucket.large = shared_address(NULL, BUCKET_LARGE_CAP * sizeof(bucket_t), PROT_WRITE | PROT_READ, MAP_SHARED | MAP_ANONYMOUS | MAP_NORESERVE, -1, 0);
        #if LOGGING == 1 || LOGGING == 0
            if (allocator.bucket.large == MAP_FAILED) {
                const int line = __LINE__;
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for data member large bucket!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for data member large bucket!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (allocator.bucket.large == MAP_FAILED) return;
        #endif 
        res = madvise(allocator.bucket.large, BUCKET_LARGE_CAP * sizeof(bucket_t), MADV_SEQUENTIAL | MADV_MERGEABLE);
        #if LOGGING == 1 || LOGGING == 0
            if (res == -1) {
                const int line = __LINE__;
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate modify memory region for data member large bucket!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify memory region for data member large bucket!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (res == -1) return;
        #endif
        allocator.bucket.small = shared_address(NULL, BUCKET_SMALL_CAP * sizeof(bucket_t), PROT_WRITE | PROT_READ, MAP_SHARED | MAP_ANONYMOUS | MAP_NORESERVE, -1, 0);
        #if LOGGING == 1 || LOGGING == 0
            if (allocator.bucket.small == MAP_FAILED) {
                const int line = __LINE__;
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for data member medium bucket!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for data member medium bucket!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (allocator.bucket.small == MAP_FAILED) return;
        #endif
        res = madvise(allocator.bucket.small, BUCKET_SMALL_CAP * sizeof(bucket_t), MADV_SEQUENTIAL | MADV_MERGEABLE);
        #if LOGGING == 1 || LOGGING == 0
            if (res == -1) {
                const int line =  __LINE__; 
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify allocator's small bucket memory region with madvise!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify allocator's small bucket memory region with madvise!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (res == -1) return;
        #endif
        allocator.bucket.medium = shared_address(NULL, BUCKET_MEDIUM_CAP * sizeof(bucket_t), PROT_WRITE | PROT_READ, MAP_SHARED | MAP_ANONYMOUS | MAP_NORESERVE, -1, 0);
        #if LOGGING == 1 || LOGGING == 0
            if (allocator.bucket.medium == MAP_FAILED) {
                const int line =  __LINE__; 
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for data member medium bucket!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for data member medium bucket!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (allocator.bucket.medium == MAP_FAILED) return;
        #endif
        res = madvise(allocator.bucket.medium, BUCKET_MEDIUM_CAP * sizeof(bucket_t), MADV_SEQUENTIAL | MADV_MERGEABLE);
        #if LOGGING == 1 || LOGGING == 0
            if (res == -1) {
                const int line = __LINE__; 
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify allocator's medium bucket memory region with madvise!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify allocator's medium bucket memory region with madvise!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (res == -1) return;
        #endif
        allocator.pool = shared_address(NULL, ALLOC_THREAD_POOL_SIZE * sizeof(threads_t), PROT_WRITE | PROT_READ, MAP_SHARED | MAP_ANONYMOUS, -1, 0);
        #if LOGGING == 1 || LOGGING == 0
            if (allocator.pool == MAP_FAILED) {
                const int line = __LINE__;
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to create allocator's internal threads!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line,  ANSI_RED "alloc_init: Failed to create allocator's internal threads!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (allocator.pool == MAP_FAILED) return;
        #endif
        res = madvise(allocator.pool, ALLOC_THREAD_POOL_SIZE * sizeof(threads_t), MADV_SEQUENTIAL | MADV_MERGEABLE);
        #if LOGGING == 1 || LOGGING == 0
            if (res == -1) {
                const int line = __LINE__;
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify memory region of allocator internal threads with madvise!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify memory region of allocator internal threads with madvise!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (res == -1) return;
        #endif
    }
    allocator.arena = init_arena_t();
    if (!allocator.arena) {
        #if LOGGING == 0 || LOGGING == 1
            const int line = __LINE__;
            #if LOGGING == 0
                printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for allocator's arena!\n.... Returning back to caller\n" ANSI_RESET);
                printer.print(__FILE__, line);
            #else 
                logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for allocator's arena!\n.... Returning back to caller\n" ANSI_RESET);
            #endif
        #endif 
        munmap_address(allocator.arena, sizeof(arena_t));
        return;
    }
}

FORCE_INLINE void debug_allocator(const size_t bytes) {
    printf("allocator.allocate: Error, failed to allocate memory for %zu\n", bytes);
    printf("Printing out information....\n");
    printf("Allocator arena state values are: arena = [ %p ], next = [ %p ], res = [ %p ], curr = [ %d ], prev = [  %d ], flag = [ %#0x ]\n", 
        allocator.arena, allocator.arena->next, allocator.arena->res, allocator.arena->curr, allocator.arena->prev, allocator.arena->flag);
    for (unsigned int i = 0; i < BUCKET_SMALL_CAP; i++) {
        if (allocator.bucket.small[i].arena) {
            printf("Allocator Bucket Small [ %d ] state values are: arena = [ %p ], next = [ %p ], res = [ %p ], curr = [ %d ], prev = [  %d ], flag = [ %#0x ] bucket_flag = [ %#0x ]\n", 
            i, allocator.bucket.small[i].arena, allocator.bucket.small[i].arena->next, allocator.bucket.small[i].arena->res, allocator.bucket.small[i].arena->curr, allocator.bucket.small[i].arena->prev, allocator.bucket.small[i].arena->flag, allocator.bucket.small[i].flag);
            if (allocator.bucket.small[i].table.entries) {
                printf("Entries at [ %d ] values are:\n", i);
                debug_entry_table_t(0x0, &allocator.bucket.small[i].table, i);
            }
        }
    }
    for (unsigned int i = 0; i < BUCKET_MEDIUM_CAP; i++) {
        if (allocator.bucket.medium[i].arena) {
            printf("Allocator Bucket Medium [ %d ] state values are: arena = [ %p ], next = [ %p ], res = [ %p ], curr = [ %d ], prev = [  %d ], flag = [ %#0x ] bucket_flag = [ %#0x ]\n", 
            i, allocator.bucket.medium[i].arena, allocator.bucket.medium[i].arena->next, allocator.bucket.medium[i].arena->res, allocator.bucket.medium[i].arena->curr, allocator.bucket.medium[i].arena->prev, allocator.bucket.medium[i].arena->flag, allocator.bucket.medium[i].flag);
            if (allocator.bucket.medium[i].table.entries) {
                printf("Entries at [ %d ] values are:\n", i);
                debug_entry_table_t(0x0, &allocator.bucket.medium[i].table, i);
            }
        }
    }
    for (unsigned int i = 0; i < BUCKET_LARGE_CAP; i++) {
        if (allocator.bucket.large[i].arena) {
            printf("Allocator Bucket Large [ %d ] state values are: arena = [ %p ], next = [ %p ], res = [ %p ], curr = [ %d ], prev = [  %d ], flag = [ %#0x ] bucket_flag = [ %#0x ]\n", 
            i, allocator.bucket.large[i].arena, allocator.bucket.large[i].arena->next, allocator.bucket.large[i].arena->res, allocator.bucket.large[i].arena->curr, allocator.bucket.large[i].arena->prev, allocator.bucket.large[i].arena->flag, allocator.bucket.large[i].flag);
            if (allocator.bucket.large[i].table.entries) {
                printf("Entries at [ %d ] values are:\n", i);
                debug_entry_table_t(0x0, &allocator.bucket.large[i].table, i);
            }
        }
    }
    printf("Printing out threading variable states\n");
    for (unsigned int i = 0; i < ALLOC_THREAD_POOL_SIZE; i++) {
        printf("Information for thread [ %d ]\n", i);
        debug_threads(allocator.pool[i]);
    } 
}

/**
    * @description: A Free Function that recrusive calls itself if arena is full and moves it forward.
    * @param bytes: The requested bytes.
    * @return: Return a memory address of desired size or big enough to hold x amount of bytes.
               Otherwise, return null, and that will indicate that everything is full.
*/
[[gnu::hot]]
void* allocate(size_t bytes) {
    char* address = NULL;
    int idx = -1;
    int_fast16_t end = 0;
    bucket_t* slot = NULL;
    if (bytes <= BUCKET_LARGE_CAP) slot = find_free_slot(bytes);
    else {
        // coalesing feature will go here...
    }
    if (slot) {
        if (!slot->arena) {
            if (allocator.arena->curr == 1) slot->arena = allocator.arena;
            else slot->arena = init_arena_t();
        }
        if (slot->flag != 0x01) {
            if (bytes <= BUCKET_SMALL_CAP) {
                end = BUCKET_SMALL_CAP;
                address = pop_from_bucket(slot, bytes);
                if (address) { memset(address, 0, bytes); return address; }
                idx = allocator.bitmap.bitmap_test(allocator.bitmap, 0, BUCKET_SMALL_CAP);
            }
            if (bytes <= BUCKET_MEDIUM_CAP && bytes >= BUCKET_SMALL_CAP) {
                end = BUCKET_MEDIUM_CAP;
                address = pop_from_bucket(slot, bytes);
                if (address) { memset(address, 0, bytes); return address; }
                idx = allocator.bitmap.bitmap_test(allocator.bitmap, 0, BUCKET_MEDIUM_CAP);
            }
            else if (bytes <= BUCKET_LARGE_CAP && bytes >= BUCKET_MEDIUM_CAP) {
                end = BUCKET_LARGE_CAP;
                address = pop_from_bucket(slot, bytes);
                if (address) { memset(address, 0, bytes); return address; }
                idx = allocator.bitmap.bitmap_test(allocator.bitmap, 0, BUCKET_LARGE_CAP);
            }

            if (slot->arena->flag != 0x01 && idx != -1) {
                slot->arena = push(slot->arena, bytes);
                if (slot->arena->flag == 0x01) {
                    slot->flag = 0x01;
                    allocator.bitmap = allocator.bitmap.bitmap_set(allocator.bitmap, idx, 0, end);
                    arena_t* full = slot->arena;
                    arena_t* fresh = init_arena_t();
                    fresh->next = full;
                    allocator.arena = fresh;
                    return allocate(bytes);
                }
                address = slot->arena->res;
                size_t offset = (uintptr_t)slot->arena->res - (uintptr_t)slot->arena->chunk;
                set(&slot->table, idx, offset, bytes, 0x01, address);
                memset(address, 0, bytes);
                return address;
            }
        }
    }
    else debug_allocator(bytes);
    return NULL;
}

/**
    * @description: A free function that determines if the following parameter that was passed into it is within a specific arena's memory region.
    * @param ptr: A memory address that can or is not apart of a arena. 
    * @return: Returns nothing if 'ptr' is not within any of the arena's memory range.   
*/
[[gnu::hot]]
FORCE_INLINE void deallocate(void* ptr) {
    if (!ptr) return;

    bucket_t* slot = NULL;
    slot = find_slot(ptr);
    if (!slot) return;

    unsigned char* base = (unsigned char*)slot->arena->chunk;
    if ((unsigned char*)ptr < base || (unsigned char*)ptr >= base + ARENA_SIZE) {
        #if LOGGING == 1 || LOGGING == 0
            char* res = write_long_cstr(0x01, 4, ANSI_RED, "ERROR ALLOCATOR.C: deallocate — ptr %p out of arena bounds\n", ANSI_RESET, ptr);
            const int line = __LINE__;
            #if LOGGING == 0
                printer.add(5, __FILE__, line, "FMI");
                printer.print(__FILE__, line);
            #else 
                logger.add(5, __FILE__, line, "FMI");
            #endif
            reset_and_free_cstr(1, res);
        #else 
            return;
        #endif
    }

    size_t offset = (size_t)((uintptr_t)ptr - (uintptr_t)slot->arena->chunk);
    const int index = find_bucket_index(slot);
    offset_entries_t* offset_entry = get_entry_t_by_offset(&slot->table, index, offset, 0x01);
    
    if (offset_entry) {
        const unsigned int bytes = offset_entry->bytes->bytes;
        push_to_bucket(slot, offset);
        __rewind(slot);
        if (slot->arena && slot->arena->chunk) memset(ptr, 0xFF, bytes);
    }
}

[[gnu::cold]]
void init_allocator_t() {
    if (!allocator.bitmap.bits)  {
        init_logger_t();
        allocator.bitmap = init_bitmap_t(BITMAP_SIZE);
        alloc_init();
    }

    if (!allocator.allocate) {
        allocator.allocate   = allocate;
        allocator.deallocate = deallocate;
    }
}

[[gnu::cold]]
[[gnu::destructor]]
FORCE_INLINE void allocator_dctor() {
    for (unsigned int i = 0;  i < ALLOC_THREAD_POOL_SIZE; i++) {
        clean_threads(allocator.pool[i]);
    }
    munmap_address(allocator.pool, ALLOC_THREAD_POOL_SIZE * sizeof(threads_t));
    bucket_t_dctor();
    if (allocator.arena) {
        //if (allocator.arena->chunk) munmap_address(allocator.arena->chunk, ARENA_SIZE);
        munmap_address(allocator.arena, sizeof(arena_t));
    }
    clean_bitmap(allocator.bitmap);   
}