#include "allocator.h"
#include <stdalign.h>
#include <stdatomic.h>
#include <stdio.h>
#include <sys/sysinfo.h>
#include <string.h>
#include <stdlib.h>
#include <sys/types.h>
#if BENCHMARK_ENV == 1
    FORCE_INLINE void init_benchmark_allocator_t();
    benchmark_allocator_t benchmark_allocator = {0};
#endif
/*
#include "allocator.h"
#include <stdalign.h>
#include <sys/sysinfo.h>
#include <string.h>
#include <stdlib.h>
#include <sys/types.h>
*/


typedef struct byte_entries_t {
    void* ptr;
    struct offset_entries_t* offset;
    struct byte_entries_t* next;
    size_t bytes;
    unsigned char inuse;
} byte_entries_t;

typedef struct offset_entries_t {
    void* ptr;
    struct byte_entries_t* bytes;
    struct offset_entries_t* next;
    size_t offset;
    unsigned char inuse;
} offset_entries_t;

typedef struct entry_table_t {
    byte_entries_t** entries;
    size_t bucket_count;
} entry_table_t;


/////////////////////////
// ENTRY TABLE SECTION //
////////////////////////


FORCE_INLINE entry_table_t* entry_table_init(entry_table_t* table) {
    if (!table) {
        table = aligned_alloc(alignof(entry_table_t), sizeof(entry_table_t));
        if (!table) return NULL;
        memset(table, 0, sizeof(entry_table_t));
    }
    table->entries = ENABLE_SHARED_MEMORY == 1 ? shared_address(NULL, 64 * sizeof(byte_entries_t*), PROT_WRITE | PROT_READ, MAP_NORESERVE, -1, 0) :
    private_address(NULL, 64 * sizeof(byte_entries_t*), PROT_WRITE | PROT_READ, MAP_NORESERVE, -1, 0);
    if (table->entries == MAP_FAILED) {
        memset(table, 0, sizeof(entry_table_t));
        free(table->entries);
        table->entries = NULL;
        table = NULL;
        return NULL;
    }
    else {
        int res = madvise(table->entries, 64 * sizeof(byte_entries_t*), MADV_SEQUENTIAL | MADV_MERGEABLE);
        if (res == -1) {
            munmap_address(table->entries, 64 * sizeof(byte_entries_t*));
            free(table);
            table = NULL;
            return NULL;
        }
    }
    memset(table->entries, 0, sizeof(byte_entries_t*) * 64);
    table->bucket_count = 64;
    return table;
}

/**
    * @description: Resizes the data member field copying over the old data to the new memory block.
    * @param table: A stack allocated addres variable 
    * @note: It resizes itself by the multiple of a numerical value that's a power of 2 i.e 64
    * @return: Nothing
*/
FORCE_INLINE entry_table_t* resize_table(entry_table_t* table) {
    size_t new_bucket_count = table->bucket_count * 2;
    byte_entries_t** new_entries =  shared_address(NULL, new_bucket_count * sizeof(byte_entries_t*), PROT_WRITE | PROT_READ, MAP_SHARED | MAP_ANONYMOUS | MAP_NORESERVE, -1, 0);
    if (new_entries == MAP_FAILED) return NULL;
    else {
        int res = madvise(new_entries, new_bucket_count * sizeof(byte_entries_t*), MADV_SEQUENTIAL | MADV_MERGEABLE);
        if (res == -1) {
            munmap_address(new_entries, sizeof(byte_entries_t*) * new_bucket_count);
            return NULL;
        }
    }
    const size_t size = table->bucket_count * sizeof(byte_entries_t*);
    memcpy(new_entries, table->entries, size);
    munmap_address(table->entries, size);
    table->entries = new_entries;
    table->bucket_count = new_bucket_count;
    return table;
}

FORCE_INLINE byte_entries_t* create_byte_entry(const size_t bytes, const unsigned char inuse, void* ptr) {
    byte_entries_t* bnode = ENABLE_SHARED_MEMORY == 0X01 ? shared_address(NULL, sizeof(byte_entries_t), PROT_WRITE | PROT_READ, MAP_NORESERVE, -1, 0) : aligned_alloc(alignof(byte_entries_t), sizeof(byte_entries_t));
    if (bnode) {
        memset(bnode, 0, sizeof(byte_entries_t)); 
        bnode->ptr = ptr; 
        bnode->offset = NULL; 
        bnode->next = NULL; 
        bnode->bytes = bytes; 
        bnode->inuse = inuse;
        return bnode;
    }
    return NULL;
}

FORCE_INLINE offset_entries_t* create_offset_entry(const size_t offset, const unsigned char inuse, void* ptr) {
    offset_entries_t* onode = ENABLE_SHARED_MEMORY == 0X01 ? shared_address(NULL, sizeof(offset_entries_t), PROT_WRITE | PROT_READ, MAP_NORESERVE, -1, 0) : aligned_alloc(alignof(offset_entries_t), sizeof(offset_entries_t));
    if (onode) {
        memset(onode, 0, sizeof(offset_entries_t)); 
        onode->ptr = ptr; 
        onode->bytes = NULL; 
        onode->next = NULL; 
        onode->offset = offset; 
        onode->inuse = inuse;
        return onode;
    }
    return NULL;
}

/**
    * @description: Free function that adds a new bijection pair, and adds the existing entries to the back.
    * @param table: A stack address variable apart of the bucket_t
    * @param idx: A variable that has been already pre-computed by the allocator's bitmap functions or a bucket function
    * @param offset: An offset generated by the arena 
    * @param bytes: The requested bytes 
    * @param inuse: Mark the entry as 0x0 not in use or 0x01 as in use 
    * @return: Return's nothing
*/
FORCE_INLINE void set(entry_table_t* table, const size_t idx, const size_t offset, const size_t bytes, const unsigned char inuse, void* ptr) {
    if (offset == 0 || bytes == 0) return;
    else if (!table || !table->entries) table = entry_table_init(table);
    else if (idx >= table->bucket_count) table = resize_table(table);

    byte_entries_t* bnode = create_byte_entry(bytes, inuse, ptr);
    offset_entries_t* onode = create_offset_entry(offset, inuse, ptr);
    if (!bnode || !onode) { free(bnode); free(onode); return; }

    bnode->offset = onode;
    onode->bytes = bnode;

    bnode->next = table->entries[idx];
    table->entries[idx] = bnode;
    return;
}

FORCE_INLINE byte_entries_t* get_entry_t_by_bytes(entry_table_t* table, const size_t idx, const size_t bytes, const unsigned char inuse) {
    if (!table || !table->entries) return NULL;
    else if (idx >= table->bucket_count) return NULL; 
    
    byte_entries_t* n = NULL;
    if (table->entries) n = table->entries[idx];
    
    while (n) {
        //if (n->next) __builtin_prefetch(n->next, 0, 1);
        unsigned int matches = (n->bytes == bytes) & (n->inuse == inuse);
        if (matches) return n;
        n = n->next;
    }
    return NULL;
}

FORCE_INLINE offset_entries_t* get_entry_t_by_offset(entry_table_t* table, const size_t idx, const size_t offset, const unsigned char inuse) {
    if (!table || !table->entries) return NULL;
    else if (idx >= table->bucket_count) return NULL;
    
    byte_entries_t* bnode = NULL;
    if (table->entries) bnode = table->entries[idx];
    while (bnode) {
        //__builtin_prefetch(bnode->next, 0, 1);
        offset_entries_t* onode = bnode->offset;
        if (onode->offset == offset && onode->inuse == inuse) return onode;
        bnode = bnode->next;
    }
    return NULL;
}

/**
    * @description: Free function that updates a bijection nodes
    * @param table: A stack address variable apart of the bucket_t
    * @param idx: A variable that has been already pre-computed by the allocator's bitmap functions or a bucket function
    * @param offset: An offset generated by the arena 
    * @param bytes: The requested bytes 
    * @param inuse: Mark the entry as 0x0 not in use or 0x01 as in use 
    * @return: Return's nothing
*/
FORCE_INLINE void update(entry_table_t* table, const size_t idx, const size_t offset, const size_t bytes, const unsigned char inuse) {
    if (!table || !table->entries) return;
    else if ((offset == 0) && (bytes == 0)) return;
    else if (idx >= table->bucket_count) return;

    byte_entries_t* bnode = table->entries[idx];
    while (bnode) {
        if (bnode->offset->offset == offset) {
            bnode->inuse = inuse;
            bnode->offset->inuse = inuse;
            break;
        }
        bnode = bnode->next;
    }
}

/**
    * @description: Free function that destroys a bijection node
    * @param table: A stack address allocated variable apart of the bucket_t
    * @param idx: A variable that has been already pre-computed by the allocator's bitmap functions or a bucket function
    * @param offset: An offset generated by the arena 
    * @param bytes: The requested bytes 
    * @param inuse: Mark the entry as 0x0 not in use or 0x01 as in use 
    * @return: Return's nothing
*/
FORCE_INLINE void destroy(entry_table_t* table, const size_t idx, const size_t offset, const size_t bytes) {
    if ((offset == 0) || (bytes == 0)) return;
    else if (!table || !table->entries || idx > table->bucket_count) return;

    byte_entries_t* prev = NULL;
    byte_entries_t* cur = table->entries[idx];
    byte_entries_t* bn = NULL;

    while (cur) {
        if ((cur->offset->offset == offset) && (cur->bytes == bytes)) { bn = cur; break; }
        prev = cur;
        cur = cur->next;
    }
    if (!bn) return;

    if (prev) prev->next = bn->next; else table->entries[idx] = bn->next;

    offset_entries_t* on = bn->offset;

    memset(bn, 0, offsetof(byte_entries_t, next));
    memset((char*)bn + offsetof(byte_entries_t, next) + sizeof(byte_entries_t*), 0,
           sizeof(byte_entries_t) - offsetof(byte_entries_t, next) - sizeof(byte_entries_t*));
    ENABLE_SHARED_MEMORY == 0X01 ? munmap_address(bn, sizeof(byte_entries_t*)) : free(bn);

    if (on) {
        memset(on, 0, offsetof(offset_entries_t, next));
        memset((char*)on + offsetof(offset_entries_t, next) + sizeof(offset_entries_t*), 0,
               sizeof(offset_entries_t) - offsetof(offset_entries_t, next) - sizeof(offset_entries_t*));
        ENABLE_SHARED_MEMORY == 0X01 ? munmap_address(on, sizeof(offset_entries_t*)) : free(on);
    }
}

FORCE_INLINE void clean(entry_table_t *table) {
    if (!table) return;
    if (table->entries) {
        for (size_t i = 0; i < table->bucket_count; i++) {
            byte_entries_t* n = table->entries[i];
            while (n && n->ptr) {
                byte_entries_t* next = n->next;
                offset_entries_t* on = n->offset;

                memset(n, 0, sizeof(byte_entries_t));
                ENABLE_SHARED_MEMORY == 1 ? munmap_address(n, sizeof(byte_entries_t)) : free(n);

                if (on) {
                    memset(on, 0, sizeof(offset_entries_t));
                    ENABLE_SHARED_MEMORY == 1 ? munmap_address(on, sizeof(offset_entries_t)) : free(on);
                }
                n = next;
            }
        }
        const size_t size = (size_t)table->bucket_count * sizeof(byte_entries_t*);
        munmap_address(table->entries, size);
    }
    memset(table, 0, sizeof(entry_table_t));
}

FORCE_INLINE void table_free_pages(entry_table_t* table) {
    if (!table->entries) return;

    int res = madvise(table->entries, table->bucket_count * sizeof(byte_entries_t*), MADV_DONTNEED);
    if (res == -1) return;
    return;
}

FORCE_INLINE void debug_entry_table_t(const unsigned char mode, entry_table_t* table, const size_t idx) {
    if (!table || !table->entries) return;
    else if (idx >= table->bucket_count) return;
    
    if (mode == 0x0) {
        byte_entries_t* bn = table->entries[idx];
        while (bn->next != NULL) {
            if (bn->offset->offset) {
                printf("Offset value is: %zu\n", bn->offset->offset);
                printf("Inuse Value is: %#0x\n", bn->inuse);
            }
            bn = bn->next;
        }
    }
    else if (mode == 0x01) {
        if (idx > table->bucket_count) return;
        byte_entries_t* n = table->entries[idx];
        while (n) {
            printf("Offset value is: %zu\n", n->bytes);
            n = n->next;
        }
    }
}

typedef struct blocks_t {
    entry_table_t     table;
    struct blocks_t** chain;
    struct blocks_t* next;
    void*            ptr;
    size_t           bytes;
    size_t           offset;
    size_t           size;
    unsigned char    inuse;
} blocks_t;

/////////////////////////
// BLOCK CHAIN SECTION //
////////////////////////

FORCE_INLINE void init_blocks_t(blocks_t* blocks) {
    blocks->size = 64;
    blocks->chain = ENABLE_SHARED_MEMORY == 1 ? shared_address(NULL, blocks->size * sizeof(blocks_t*), PROT_WRITE | PROT_READ, MAP_NORESERVE, -1, 0) :
     aligned_alloc(alignof(blocks_t*), blocks->size * sizeof(blocks_t*));
    if (blocks->chain == MAP_FAILED) return;
    else if (ENABLE_SHARED_MEMORY) {
        int res = madvise(blocks->chain, blocks->size * sizeof(blocks_t*), MADV_SEQUENTIAL | MADV_MERGEABLE);
        if (res == -1) return;
    }
    memset(blocks->chain, 0, blocks->size * sizeof(blocks_t*));
    return;
}

FORCE_INLINE blocks_t* create_block_t() {
    blocks_t* block = ENABLE_SHARED_MEMORY == 1 ? shared_address(NULL, sizeof(blocks_t), PROT_WRITE | PROT_READ, MAP_NORESERVE, -1, 0) : aligned_alloc(alignof(blocks_t), sizeof(blocks_t));
    if (!block) return NULL;
    memset(block, 0, sizeof(blocks_t));
    return block;
}

FORCE_INLINE void resize_blocks(blocks_t* blocks) {
    if (!blocks->chain) return; 
    const size_t old = blocks->size;
    const size_t new = (blocks->size * 2) * sizeof(blocks_t*);
    
    blocks_t** chain = ENABLE_SHARED_MEMORY == 1 ? 
        shared_address(NULL, new * sizeof(blocks_t*), PROT_WRITE | PROT_READ, MAP_NORESERVE, -1, 0) :
        aligned_alloc(alignof(blocks_t*), new * sizeof(blocks_t*));
    if (chain == MAP_FAILED) return;
    else if (ENABLE_SHARED_MEMORY) {
        int res = madvise(chain, new * sizeof(blocks_t*), MADV_SEQUENTIAL | MADV_MERGEABLE);
        if (res == -1) {
            if (chain) { munmap_address(chain, new * sizeof(blocks_t*)); chain = NULL; }
            return;
        }
    }

    void* ptr = blocks->chain;
    memcpy(chain, ptr, old);
    munmap_address(ptr, old);
    blocks->size = new;
    
    return;
}

FORCE_INLINE unsigned char is_mergeable(entry_table_t* table, const size_t idx, const size_t bytes) {
    if (bytes == 0 || !table || !table->entries) return 0x0;
    else if (idx > table->bucket_count) return 0x0;

    byte_entries_t* seed = table->entries[idx];
    while (seed) {
        if (seed->inuse == 0x0 && seed->offset) {
            if (seed->offset->offset) {
                size_t accumulated = seed->bytes;
                size_t probe_offset = seed->offset->offset + seed->bytes;
                while (accumulated < bytes) {
                    offset_entries_t* nxt = get_entry_t_by_offset(table, idx, probe_offset, 0x0);
                    if (!nxt) break;
                    accumulated += nxt->bytes->bytes;
                    probe_offset += nxt->bytes->bytes;
                }
                if (accumulated >= bytes) return 0x01;
            }
        }
        seed = seed->next;
    }
    return 0x0;
}

FORCE_INLINE void merge(blocks_t* blocks, entry_table_t* table, const size_t idx, const size_t bytes) {
    if (!blocks->chain) init_blocks_t(blocks);
    else if (idx > blocks->size) resize_blocks(blocks);

    byte_entries_t* seed = table->entries[idx];
    while (seed) {
        if (seed->inuse == 0x0) {
            size_t accumulated = seed->bytes;
            size_t probe_offset = seed->offset->offset + seed->bytes;
            while (accumulated < bytes) {
                offset_entries_t* nxt = get_entry_t_by_offset(table, idx, probe_offset, 0x0);
                if (!nxt) break;
                accumulated += nxt->bytes->bytes;
                probe_offset += nxt->bytes->bytes;
            }
            if (accumulated >= bytes) break;
        }
        seed = seed->next;
    }
    if (!seed) return;

    size_t total = 0;
    size_t cur_offset = seed->offset->offset;
    blocks_t* head = NULL;
    blocks_t* tail = NULL;

    while (total < bytes) {
        offset_entries_t* oe = get_entry_t_by_offset(table, idx, cur_offset, 0x0);
        if (!oe) break;
        byte_entries_t* piece_entry = oe->bytes;
        size_t piece_bytes = piece_entry->bytes;
        size_t need = bytes - total;

        blocks_t* node = create_block_t();
        if (!node) break;
        node->offset = cur_offset;
        node->inuse = 0x01;
        node->next = NULL;

        if (piece_bytes > need) {
            size_t leftover_bytes = piece_bytes - need;
            size_t leftover_offset = cur_offset + need;
            void* leftover_ptr = (char*)piece_entry->ptr + need;

            node->ptr = piece_entry->ptr;
            node->bytes = need;

            destroy(table, idx, cur_offset, piece_bytes);
            set(table, idx, leftover_offset, leftover_bytes, 0x0, leftover_ptr);

            total += need;
        } else {
            node->ptr = piece_entry->ptr;
            node->bytes = piece_bytes;

            total += piece_bytes;
            cur_offset += piece_bytes;

            destroy(table, idx, node->offset, piece_bytes);
        }

        if (!head) head = node; else tail->next = node;
        tail = node;
    }

    if (!head) return;
    tail->next = blocks->chain[idx];
    blocks->chain[idx] = head;
}

FORCE_INLINE void update_block_t_by_offset(blocks_t* blocks, const size_t idx, const size_t offset, const unsigned char inuse) {
    if (!blocks) return;
    else if (!blocks->chain || !blocks->chain[idx]) return;

    blocks_t* seed = blocks->chain[idx];
    while (seed) {
        if ((seed->offset == offset) && (seed->inuse == inuse)) {
            seed->inuse = 0x0;
            return;
        }
        seed = seed->next;
    }
}

FORCE_INLINE blocks_t* get_block_t_by_offset(blocks_t* blocks, const size_t idx, const size_t offset, const unsigned char inuse) {
    if (!blocks) return NULL;
    else if (!blocks->chain || !blocks->chain[idx]) return NULL;

    blocks_t* seed = blocks->chain[idx];
    while (seed) {
        if ((seed->offset == offset) && (seed->inuse == inuse)) return seed;
        seed = seed->next;
    }
    return NULL;
}

FORCE_INLINE void blocks_t_free_pages(blocks_t* blocks) {
    if (!blocks->chain) return;
    int res = madvise(blocks->chain, blocks->size * sizeof(blocks_t*), MADV_DONTNEED);
    if (res == -1) return;
}

FORCE_INLINE void block_t_dctor(blocks_t* blocks) {
    blocks_t* seed = blocks;
    while (seed) {
        blocks_t* node = seed->next;
        if (seed) {
            memset(seed, 0, sizeof(blocks_t));
            ENABLE_SHARED_MEMORY == 1 ? munmap_address(seed, sizeof(blocks_t)) : free(seed);
        }
        seed = node;
    }
    blocks = NULL;
}

typedef struct bucket_t {
    blocks_t       blocks;
    arena_t*       arena;
    unsigned char  flag;
} bucket_t;

typedef struct huge_slot_t {
    blocks_t       blocks;  
    size_t         capacity; /* Represents the amount of memory it can hold */
    size_t         space;   /* capacity >= space otherwise slot is full */
} huge_slot_t;
FORCE_INLINE void* coalescing(const size_t bytes); /* Defined in Allocator Section */
FORCE_INLINE size_t find_bucket_index(bucket_t* slot);


/////////////////////
// BUCKET SECTION //
///////////////////

FORCE_INLINE void* thread_update(struct function_t* meta); /* Defined in Threading Section. */

/**
    * @description: A Free function that finds a free slot based on the size at O(n). 
    * @param sz: can be a numeric value of size: 64, 128, or 256. 
    * @return: Returns a slot right after checking the bucket's bitmap.
    * @note: if nothing is returned, that means all of the slots from small, medium and large are occupied. 
*/
FORCE_INLINE bucket_t* find_free_slot(size_t sz) {
    size_t idx = SIZE_MAX;
    
    if (sz <= BUCKET_SMALL_CAP) {
        idx = allocator.bitmap.bitmap_test(allocator.bitmap, 0, BUCKET_SMALL_CAP - 1);
        #if LOGGING == 1
            #if LOGLEVEL == 0  
                printf("[find_free_slot] small idx: %d\n", idx);
            #elif LOGLEVEL > 1
                // TODO: Include the logger variable here and its functions
            #endif
        #endif
        if (idx <= USHRT_MAX && idx != SIZE_MAX) return &allocator.bucket.small[idx];
    }
    else if (sz <= BUCKET_MEDIUM_CAP) {
        idx = allocator.bitmap.bitmap_test(allocator.bitmap, 0, BUCKET_MEDIUM_CAP - 1);
        #if LOGGING == 1
            #if LOGLEVEL == 0 
                printf("[find_free_slot] medium idx: %d\n", idx);
            #elif LOGLEVEL > 1
                // TODO: Include the logger variable here and its functions
            #endif
        #endif 
        if (idx <= USHRT_MAX && idx != SIZE_MAX) return &allocator.bucket.medium[idx];
    }
    else if (sz <= BUCKET_LARGE_CAP) {
        idx = allocator.bitmap.bitmap_test(allocator.bitmap, 0, BUCKET_LARGE_CAP - 1);
        #if LOGGING == 1
            #if LOGLEVEL == 0 
                printf("[find_free_slot] large idx: %d\n", idx);
            #elif LOGLEVEL > 1
                // TODO: Include the logger variable here and its functions
            #endif
        #endif 
        if (idx <= USHRT_MAX && idx != SIZE_MAX) return &allocator.bucket.large[idx];
    }
    return NULL;
}

/**
    * @description: A Free function that finds the specific bucket, which contains an arena that the memory address came from or not.
    * @param ptr: A memory address that came from the arena. 
    * @return: Returns null if nothing was found.
    * @note: If nothing was found, that means the 'ptr' memory address is from a memory address that is not associated with the arena. 
             Or an address that was allocated on the heap. 
*/
FORCE_INLINE bucket_t* find_slot(void* ptr) {
    uintptr_t p = (uintptr_t)ptr;

    for (size_t i = 0; i < BUCKET_SMALL_CAP; i++) {
        bucket_t* b = &allocator.bucket.small[i];
        if (b->arena && p >= (uintptr_t)b->arena->chunk && p < (uintptr_t)b->arena->chunk + ARENA_SIZE) {
            size_t offset = (size_t)(p - (uintptr_t)b->arena->chunk);
            if (get_entry_t_by_offset(&b->blocks.table, i, offset, 0x01)) {
                if (b->flag == 0x01 && b->arena->flag == 0x01) {
                    b->flag = 0x0; b->arena->flag = 0x0;
                    allocator.bitmap = allocator.bitmap.bitmap_clear(allocator.bitmap, i, 0, BUCKET_SMALL_CAP - 1);
                }
                return b;
            }
            blocks_t* blocks = get_block_t_by_offset(&b->blocks, i, offset, 0x01);
            if (blocks) return b;
        }
    }
    for (size_t i = 0; i < BUCKET_MEDIUM_CAP; i++) {
        bucket_t* b = &allocator.bucket.medium[i];
        if (b->arena && p >= (uintptr_t)b->arena->chunk && p < (uintptr_t)b->arena->chunk + ARENA_SIZE) {
            size_t offset = (size_t)(p - (uintptr_t)b->arena->chunk);
            if (get_entry_t_by_offset(&b->blocks.table, i, offset, 0x01)) {
                if (b->flag == 0x01 && b->arena->flag == 0x01) {
                    b->flag = 0x0; b->arena->flag = 0x0;
                    allocator.bitmap = allocator.bitmap.bitmap_clear(allocator.bitmap, i, 0, BUCKET_MEDIUM_CAP - 1);
                }
                return b;
            }
            blocks_t* blocks = get_block_t_by_offset(&b->blocks, i, offset, 0x01);
            if (blocks) return b;
        }
    }
    for (size_t i = 0; i < BUCKET_LARGE_CAP; i++) {
        bucket_t* b = &allocator.bucket.large[i];
        if (b->arena && p >= (uintptr_t)b->arena->chunk && p < (uintptr_t)b->arena->chunk + ARENA_SIZE) {
            size_t offset = (size_t)(p - (uintptr_t)b->arena->chunk);
            if (get_entry_t_by_offset(&b->blocks.table, i, offset, 0x01)) {
                if (b->flag == 0x01 && b->arena->flag == 0x01) {
                    b->flag = 0x0; b->arena->flag = 0x0;
                    allocator.bitmap = allocator.bitmap.bitmap_clear(allocator.bitmap, i, 0, BUCKET_LARGE_CAP - 1);
                }
                return b;
            }
            blocks_t* blocks = get_block_t_by_offset(&b->blocks, i, offset, 0x01);
            if (blocks) return b;
        }
    }
    return NULL;
}

FORCE_INLINE size_t find_bucket_index(bucket_t* slot) {
    if (!slot) return SIZE_MAX;
    if (slot >= allocator.bucket.small && slot < allocator.bucket.small + BUCKET_SMALL_CAP) return (size_t)(slot - allocator.bucket.small);
    if (slot >= allocator.bucket.medium && slot < allocator.bucket.medium + BUCKET_MEDIUM_CAP) return (size_t)(slot - allocator.bucket.medium);
    if (slot >= allocator.bucket.large && slot < allocator.bucket.large + BUCKET_LARGE_CAP) return (size_t)(slot - allocator.bucket.large);
    return SIZE_MAX;
}

/**
    * @description: Function that returns the size where it came from 
    * @param slot: Pointer variable that possibly comes from one of the bucket's memory regions
    * @return: Returns either BUCKET_SMALL_CAP, BUCKET_MEDIUM_CAP, or BUCKET_LARGE_CAP, or returns 0
*/
FORCE_INLINE size_t find_bucket_size(const bucket_t* slot) {
    uintptr_t addr = (uintptr_t)slot;
    uintptr_t small_start  = (uintptr_t)allocator.bucket.small;
    uintptr_t small_end    = small_start  + BUCKET_SMALL_CAP  * sizeof(bucket_t);
    uintptr_t medium_start = (uintptr_t)allocator.bucket.medium;
    uintptr_t medium_end   = medium_start + BUCKET_MEDIUM_CAP * sizeof(bucket_t);
    
    if (addr >= small_start && addr < small_end)   return BUCKET_SMALL_CAP;
    if (addr >= medium_start && addr < medium_end) return BUCKET_MEDIUM_CAP;

    uintptr_t large_start = (uintptr_t)allocator.bucket.large;
    uintptr_t large_end   = large_start + BUCKET_LARGE_CAP * sizeof(bucket_t);
    if (addr >= large_start && addr < large_end) return BUCKET_LARGE_CAP;
    return 0;
}

/**
    * @description: A Free Function that pushes the unused memory addresses to bucket.
        It is used with deallocation function
    * @param b: A specific bucket that will now have been updated 
*/
FORCE_INLINE void push_to_bucket(bucket_t* slot, size_t offset) {
    size_t idx = find_bucket_index(slot);
    if (idx == SIZE_MAX) return;
    
    offset_entries_t* onode = get_entry_t_by_offset(&slot->blocks.table, idx, offset, 0x01);
    if (!onode) return;
    update(&slot->blocks.table, idx, offset, onode->bytes->bytes, 0x0);

    return;
}

/**
    * @description: A free function that pops off a memory address that is not in use based on the requested size
    * @param slot: The slot which is bucket_t that has memory addresses to be used. 
    * @param bytes: the requested bytes 
    * @return: Returns null if bucket field is null or if bucket == slot->arena->chunk  
*/
FORCE_INLINE void* pop_from_bucket(bucket_t* slot, size_t bytes) {
    size_t idx = find_bucket_index(slot);
    if (idx == SIZE_MAX) return NULL;

    byte_entries_t* bnode = get_entry_t_by_bytes(&slot->blocks.table, idx,  bytes, 0x0);
    if (!bnode || bnode->ptr == NULL) return coalescing(bytes);
    
    void* address = NULL;
    if (bnode && bnode->offset) {
        update(&slot->blocks.table, idx, bnode->offset->offset, bnode->bytes, 0x01);
        //slot->arena = push(slot->arena, bytes);
        address = bnode->ptr;
    }
    
    /*#if LOGGING == 0 || LOGGING == 1
        const int line = __LINE__;
        char* res = write_long_cstr(0x01, 1, "Entry variable is: [ %p ]\n", tmp);
        #if LOGGING == 0
            printer.add(0, __FILE__, line, res);
            printer.print(__FILE__, line);
        #else
            logger.add(0, __FILE__, line, res);
        #endif
        cstr_size(1, res) < ALLOC_THRESHOLD ? reset_and_free_cstr(1, res) : unmap_cstr(1, res);
    #endif*/
    return address;
}

[[gnu::cold]]
FORCE_INLINE void bucket_t_dctor() {
    unsigned int small = 0;
    unsigned int medium = 0;
    while (small < BUCKET_SMALL_CAP) {
        arena_t* arena = allocator.bucket.small[small].arena;
        bucket_t slot = allocator.bucket.small[small];
        entry_table_t table = atomic_load_explicit(&slot.blocks.table, memory_order_relaxed);
        if (table.entries) clean(&table);
        if (arena) {
            if (arena->chunk) munmap_address(arena->chunk, ARENA_SIZE + 1);
            munmap_address(arena, sizeof(arena_t));
            arena = NULL;
        }
        if (slot.blocks.chain && slot.blocks.chain[small]) block_t_dctor(slot.blocks.chain[small]);
        small = small + 1;
    }
    munmap_address(allocator.bucket.small, BUCKET_SMALL_CAP * sizeof(bucket_t));
    while (medium < BUCKET_MEDIUM_CAP) {
        //arena_t* arena = allocator.bucket.medium[medium].arena;
        bucket_t slot = allocator.bucket.medium[medium];
        entry_table_t table = atomic_load_explicit(&slot.blocks.table, memory_order_relaxed);
        if (table.entries) clean(&table);
        /*if (arena != NULL) {
            if (arena->chunk) munmap_address(arena->chunk, ARENA_SIZE + 1);
            munmap_address(arena, sizeof(arena_t));
        }*/
        if (slot.blocks.chain && slot.blocks.chain[medium]) block_t_dctor(slot.blocks.chain[medium]);
        medium = medium + 1;
    }
    munmap_address(allocator.bucket.medium, BUCKET_MEDIUM_CAP * sizeof(bucket_t));
    unsigned int large = 0;
    while (large < BUCKET_LARGE_CAP) {
        arena_t* arena = allocator.bucket.large[large].arena;
        bucket_t slot = allocator.bucket.large[large];
        entry_table_t table = atomic_load_explicit(&slot.blocks.table, memory_order_relaxed);
        if (table.entries) clean(&table);
        if (arena) {
            if (arena->chunk) munmap_address(arena->chunk, ARENA_SIZE + 1);
            munmap_address(arena, sizeof(arena_t));
        }
        if (slot.blocks.chain && slot.blocks.chain[large]) block_t_dctor(slot.blocks.chain[large]);
        large = large + 1;
    }
    munmap_address(allocator.bucket.large, BUCKET_LARGE_CAP * sizeof(bucket_t));
}

/**
    * @description: A Free function that rewinds the arena back to a safe spot, based on certain conditions. 
    * @param slot: A raw pointer that has been allocated on the heap that is apart of the allocator.bucket
    * @note: It will rewind all the way to the very last entry, and if that entry is not inuse, it will destroy the whole entry_table_t chain.
    * @return Nothing
*/
FORCE_INLINE void __rewind(bucket_t* slot) {
    size_t idx = find_bucket_index(slot);
    byte_entries_t* bnode = slot->blocks.table.entries[idx];
    while (bnode && bnode->offset->inuse == 0x0) {
        byte_entries_t* next = bnode->next;
        size_t offset = bnode->offset->offset;
        if (next) slot->arena = pop(slot->arena, next->offset->offset);
        destroy(&slot->blocks.table, idx, offset, bnode->bytes);
        bnode = next;
    }
    if (!bnode) {
        clear_arena_t(slot->arena);
        table_free_pages(&slot->blocks.table);
    }
}


////////////////////////
// THREADING SECTION //
//////////////////////

FORCE_INLINE void allocator_huge_update_slots(const size_t start, const size_t end); /* Defined in Allocator section */
FORCE_INLINE void* thread_update_thread_pool(struct function_t* meta); 

FORCE_INLINE void* thread_update(struct function_t* meta) {
    void** args = routine_metadata_arguments(meta);
    if (!args) pthread_exit(NULL);
    
    entry_table_t* table = (entry_table_t*)args[0];
    const size_t idx = *(size_t*)args[1];
    const size_t offset = *(size_t*)args[2];
    const size_t bytes = *(size_t*)args[3];
    const unsigned char inuse = *(unsigned char*)args[4];
    atomic_size_t* done = (atomic_size_t*)args[5];
    
    update(table, idx, offset, bytes, inuse);
    atomic_store_explicit(done, 1, memory_order_release);
    pthread_exit(NULL);
}

FORCE_INLINE void* thread_destroy(struct function_t* meta) {
    void** args = routine_metadata_arguments(meta);
    if (!args) pthread_exit(NULL);
    
    //_Atomic(entry_table_t)* table = (_Atomic(entry_table_t)*)args[0];
    //const size_t idx = *(size_t*)args[1];
    //const size_t offset = *(size_t*)args[2];
    //const size_t bytes = *(size_t*)args[3];
    
    //destroy(table, idx, offset, bytes);
    pthread_exit(NULL);
}

FORCE_INLINE void* thread_update_thread_pool(struct function_t* meta) {
    void** args = routine_metadata_arguments(meta);
    if (!args) pthread_exit(NULL);
    
    atomic_size_t* done = (atomic_size_t*)args[0];

    update_thread_pool(allocator.pool, ALLOC_THREAD_POOL_SIZE);
    atomic_store_explicit(done, 1, memory_order_release);
    pthread_exit(NULL);
}

FORCE_INLINE void* thread_create_thread_pool_range(struct function_t* meta) {
    void** args = routine_metadata_arguments(meta);
    if (!args) pthread_exit(NULL);
    
    unsigned char mode = *(unsigned char*)args[0], attr = *(unsigned char*)args[1], locked = *(unsigned char*)args[2], stack = *(unsigned char*)args[3];
    size_t start = *(size_t*)args[4], end = *(size_t*)args[5];
    atomic_size_t* done = (atomic_size_t*)args[6];

    create_thread_pool_range(allocator.pool, mode, attr, locked, stack, start, end);
    atomic_store_explicit(done, 1, memory_order_release);
    pthread_exit(NULL);
}

FORCE_INLINE void* thread_update_block_t_by_offset(struct function_t* meta) {
    void** args = routine_metadata_arguments(meta);
    if (!args) pthread_exit(NULL);

    blocks_t* blocks = (blocks_t*)args[0];
    const size_t index = (size_t)(uintptr_t)args[1];
    const size_t offset = (size_t)(uintptr_t)args[2];
    const unsigned char inuse = (unsigned char)(uintptr_t)args[3];
    atomic_size_t* done = (atomic_size_t*)args[4];

    update_block_t_by_offset(blocks, index, offset, inuse);
    atomic_store_explicit(done, 1, memory_order_release);
    pthread_exit(NULL);
}

FORCE_INLINE void* thread_rewind(struct function_t* meta) {
    void** args = routine_metadata_arguments(meta);
    if (!args) pthread_exit(NULL);
    
    bucket_t* slot = (bucket_t*)args[0];
    atomic_size_t* done = (atomic_size_t*)args[1];
    
    __rewind(slot);
    atomic_store_explicit(done, 1, memory_order_release);
    pthread_exit(NULL);
}

FORCE_INLINE void* thread_ensure_capacity(struct function_t* meta) {
    void** args = routine_metadata_arguments(meta);
    if (!args) pthread_exit(NULL);
    const size_t bytes = *(size_t*)args[0];
    atomic_size_t* cap = (atomic_size_t*)args[1];
    char* region = (char*)args[2];
    atomic_size_t* done = (atomic_size_t*)args[3];

    size_t end = atomic_load_explicit(cap, memory_order_acquire);
    size_t new_end = end;
    
    if (bytes > end) {
        while (new_end < bytes) new_end *= 2;
        if (atomic_compare_exchange_strong(cap, &end, new_end)) region = remap_address(region, end, new_end);
    }
    atomic_store_explicit(done, 1, memory_order_release);
    pthread_exit(NULL);
}

FORCE_INLINE void* thread_allocator_huge_update_slots(struct function_t* meta) {
    void** args = routine_metadata_arguments(meta);
    if (!args) pthread_exit(NULL);
    
    size_t begin = *(size_t*)args[0];
    size_t end   = *(size_t*)args[1];
    atomic_size_t* done = (atomic_size_t*)args[2];

    allocator_huge_update_slots(begin, end);
    atomic_store_explicit(done, 1, memory_order_release);
    pthread_exit(NULL);
}


////////////////////////
// ALLOCATOR SECTION //
//////////////////////


typedef struct huge_block_allocator_t {
    bitmap_t        bitmap;
    char*           region;
    huge_slot_t*    slots;
    size_t          slot_cap;
    atomic_size_t   allocator_cap;
    atomic_size_t   done; /* Used for lock free syncing threads */
} huge_block_allocator_t;

FORCE_INLINE void init_huge_allocator(void);
FORCE_INLINE void allocator_huge_resize_slots(huge_slot_t* slot, const size_t size);
FORCE_INLINE void* allocator_huge_update_slot(huge_slot_t* slot, const size_t index, const size_t end, size_t bytes);
FORCE_INLINE unsigned char overcommit(size_t bytes);

allocator_t allocator = {0};
void* allocate(const size_t bytes);

[[gnu::cold]]
FORCE_INLINE void allocator_init_arena_t(void) {
    allocator.arena = init_arena_t();
    if (!allocator.arena) {
        #if LOGGING == 0 || LOGGING == 1
            const int line = __LINE__;
            #if LOGGING == 0
                printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for allocator's arena!\n.... Returning back to caller\n" ANSI_RESET);
                printer.print(__FILE__, line);
            #else 
                logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for allocator's arena!\n.... Returning back to caller\n" ANSI_RESET);
            #endif
        #endif 
        munmap_address(allocator.arena, sizeof(arena_t));
        return;
    }
}

[[gnu::cold]]
// TODO: Need to make sure that MADV_MERGEABLE enabled does not consume a lot of processing power; use with care.
FORCE_INLINE void allocator_init_buckets_t(void) {
    int res = 0;
    if (!allocator.bucket.small) {
        allocator.bucket.large = shared_address(NULL, BUCKET_LARGE_CAP * sizeof(bucket_t), PROT_WRITE | PROT_READ, MAP_NORESERVE, -1, 0);
        #if LOGGING == 1 || LOGGING == 0
            if (allocator.bucket.large == MAP_FAILED) {
                const int line = __LINE__;
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for data member large bucket!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for data member large bucket!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (allocator.bucket.large == MAP_FAILED) return;
        #endif 
        res = madvise(allocator.bucket.large, BUCKET_LARGE_CAP * sizeof(bucket_t), MADV_SEQUENTIAL | MADV_MERGEABLE);
        #if LOGGING == 1 || LOGGING == 0
            if (res == -1) {
                const int line = __LINE__;
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate modify memory region for data member large bucket!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify memory region for data member large bucket!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (res == -1) return;
        #endif
        allocator.bucket.small = shared_address(NULL, BUCKET_SMALL_CAP * sizeof(bucket_t), PROT_WRITE | PROT_READ, MAP_NORESERVE, -1, 0);
        #if LOGGING == 1 || LOGGING == 0
            if (allocator.bucket.small == MAP_FAILED) {
                const int line = __LINE__;
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for data member medium bucket!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for data member medium bucket!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (allocator.bucket.small == MAP_FAILED) return;
        #endif
        res = madvise(allocator.bucket.small, BUCKET_SMALL_CAP * sizeof(bucket_t), MADV_SEQUENTIAL | MADV_MERGEABLE);
        #if LOGGING == 1 || LOGGING == 0
            if (res == -1) {
                const int line =  __LINE__; 
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify allocator's small bucket memory region with madvise!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify allocator's small bucket memory region with madvise!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (res == -1) return;
        #endif
        allocator.bucket.medium = shared_address(NULL, BUCKET_MEDIUM_CAP * sizeof(bucket_t), PROT_WRITE | PROT_READ,  MAP_NORESERVE, -1, 0);
        #if LOGGING == 1 || LOGGING == 0
            if (allocator.bucket.medium == MAP_FAILED) {
                const int line =  __LINE__; 
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for data member medium bucket!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to allocate memory for data member medium bucket!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (allocator.bucket.medium == MAP_FAILED) return;
        #endif
        res = madvise(allocator.bucket.medium, BUCKET_MEDIUM_CAP * sizeof(bucket_t), MADV_SEQUENTIAL | MADV_MERGEABLE);
        #if LOGGING == 1 || LOGGING == 0
            if (res == -1) {
                const int line = __LINE__; 
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify allocator's medium bucket memory region with madvise!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify allocator's medium bucket memory region with madvise!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (res == -1) return;
        #endif
    }
}

[[gnu::cold]]
FORCE_INLINE void allocator_init_threads_t(void) {
    int res = 0;
    if (!allocator.pool) {
        allocator.pool = shared_address(NULL, ALLOC_THREAD_POOL_SIZE * sizeof(threads_t), PROT_WRITE | PROT_READ, MAP_NORESERVE, -1, 0);
        #if LOGGING == 1 || LOGGING == 0
            if (allocator.pool == MAP_FAILED) {
                const int line = __LINE__;
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to create allocator's internal threads!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line,  ANSI_RED "alloc_init: Failed to create allocator's internal threads!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (allocator.pool == MAP_FAILED) return;
        #endif
        res = madvise(allocator.pool, ALLOC_THREAD_POOL_SIZE * sizeof(threads_t), MADV_SEQUENTIAL | MADV_MERGEABLE);
        #if LOGGING == 1 || LOGGING == 0
            if (res == -1) {
                const int line = __LINE__;
                #if LOGGING == 0
                    printer.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify memory region of allocator internal threads with madvise!\n.... Returning back to caller\n" ANSI_RESET);
                    printer.print(__FILE__, line);
                #else 
                    logger.add(5, __FILE__, line, ANSI_RED "alloc_init: Failed to modify memory region of allocator internal threads with madvise!\n.... Returning back to caller\n" ANSI_RESET);
                #endif
            }
        #else 
            if (res == -1) return;
        #endif

        static const unsigned char mode = 0x0, attr = 0x01, locked = 0x0, stack = 0x0;
        static const size_t start = 1, end = ALLOC_THREAD_POOL_SIZE;
        allocator.pool[0] = init_threads_t(mode, attr, locked, stack);
        routine_metadata(&allocator.pool[0], 7, &mode, &attr, &locked, &stack, &start, &end, &allocator.huge->done);
        create_thread(&allocator.pool[0], thread_create_thread_pool_range);
    }
}

FORCE_INLINE void allocator_resize_bitmap(bitmap_t* bitmap, const size_t new_size) {
    if (!bitmap->bits) return;

    size_t size = bitmap->n_bytes;
    void* map = bitmap->bits;
    
    bitmap->bits = size < ALLOC_THRESHOLD ? realloc(bitmap->bits, new_size) : remap_address(bitmap->bits, size, new_size);
    if (!bitmap->bits) return;
    
    memset(bitmap->bits, 0xFF, new_size);
    memcpy(bitmap->bits, map, size);
    size < ALLOC_THRESHOLD ? free(map) : munmap_address(map, size);
    bitmap->n_bytes = new_size;
    return;
}

FORCE_INLINE void* allocator_byte_request(size_t bytes) {
    if (bytes == 0 || !allocator.huge) return NULL;
    else if (!allocator.huge->region) return NULL;
    else if ((bytes & (bytes - 1)) != 0) bytes = 1ULL << (64 - __builtin_clzll(bytes - 1));

    while (!atomic_load_explicit(&allocator.huge->done, memory_order_acquire));
    
    size_t pages_needed = (size_t)((bytes + HUGE_PAGE_SIZE - 1) / HUGE_PAGE_SIZE);
    if (pages_needed == 0) return NULL;
    else if (!overcommit(bytes)) return NULL;
    
    char* address = NULL;
    threads_t* t1 = find_thread_t(allocator.pool, ALLOC_THREAD_POOL_SIZE);
    if (!t1) return NULL;

    routine_metadata(t1, 4, &bytes, &allocator.huge->allocator_cap, allocator.huge->region, &allocator.huge->done);
    create_thread(t1,  thread_ensure_capacity);
    
    while (!atomic_load_explicit(&allocator.huge->done, memory_order_acquire)){};
    atomic_store_explicit(&allocator.huge->done, 0, memory_order_release);

    const size_t size = atomic_load_explicit(&allocator.huge->allocator_cap, memory_order_relaxed);
    if (size > bytes) {
        size_t slot_size = allocator.huge->slot_cap;
        size_t index = allocator.huge->bitmap.bitmap_test(allocator.huge->bitmap, 0, allocator.huge->slots[slot_size - 1].capacity);
        if (index == SIZE_MAX) {
            allocator_resize_bitmap(&allocator.huge->bitmap, allocator.huge->bitmap.n_bytes * 2);
            allocator_huge_resize_slots(allocator.huge->slots, allocator.huge->slots[slot_size - 1].capacity * 2);
            if (!allocator.huge->slots || !allocator.huge->bitmap.bits) return NULL; 
            index = allocator.huge->bitmap.bitmap_test(allocator.huge->bitmap, 0, allocator.huge->slots[slot_size - 1].capacity);
        } 
        else if (is_mergeable(&allocator.huge->slots[index].blocks.table, index, bytes)) {
            merge(&allocator.huge->slots[index].blocks, &allocator.huge->slots[index].blocks.table, index, bytes);
            const size_t rhs = allocator.huge->slots[index].blocks.offset + allocator.huge->slots[index].blocks.bytes;
            if (allocator.huge->slots[index].space >= rhs) {
                allocator.huge->slots[index].space -= rhs; /* Below this line the code is wrong possibly */
                if (!allocator.huge->slots[index].blocks.chain[index]->next) blocks_t_free_pages(allocator.huge->slots[index].blocks.chain[index]);
            }
            else {
                allocator.huge->bitmap = allocator.huge->bitmap.bitmap_set(allocator.huge->bitmap, index, 0, allocator.huge->slots[slot_size - 1].capacity);
                return allocate(bytes);
            }
            
            address = allocator.huge->slots[index].blocks.chain[index]->ptr;
            memset(address, 0, bytes);
            return address;
        }
        else address = allocator_huge_update_slot(&allocator.huge->slots[index], index, allocator.huge->slots[slot_size - 1].capacity, bytes);
        memset(address, 0, bytes);  
    }

    return address;
}

FORCE_INLINE void* coalescing(const size_t bytes) {
    
    for (size_t i = 0; i < BUCKET_SMALL_CAP; i++) {
        bucket_t* b = &allocator.bucket.small[i];
        if (b->arena && b->flag == 0x0 && b->arena->flag == 0x0) {
            if (is_mergeable(&b->blocks.table, i, bytes) == 0x01) {
                merge(&b->blocks, &b->blocks.table, i, bytes);
                if (b->blocks.chain[i]) return b->blocks.chain[i]->ptr;
            }
        }
    }

    for (size_t i = 0; i < BUCKET_MEDIUM_CAP; i++) {
        bucket_t* b = &allocator.bucket.medium[i];
        if (b->arena && b->flag == 0x0 && b->arena->flag == 0x0) {
            if (is_mergeable(&b->blocks.table, i, bytes) == 0x01) {
                merge(&b->blocks, &b->blocks.table, i, bytes);
                if (b->blocks.chain[i]) return b->blocks.chain[i]->ptr;
            }
        }
    }

    for (size_t i = 0; i < BUCKET_LARGE_CAP; i++) {
        bucket_t* b = &allocator.bucket.large[i];
        if (b->arena && b->flag == 0x0 && b->arena->flag == 0x0) {
            if (is_mergeable(&b->blocks.table, i, bytes) == 0x01) {
                merge(&b->blocks, &b->blocks.table, i, bytes);
                if (b->blocks.chain[i]) return b->blocks.chain[i]->ptr;
            }
        }
    }

    return NULL;
}

FORCE_INLINE void debug_allocator(const size_t bytes) {
    printf("allocator.allocate: Error, failed to allocate memory for %zu\n", bytes);
    printf("Printing out information....\n");
    printf("Allocator arena state values are: arena = [ %p ], next = [ %p ], res = [ %p ], curr = [ %d ], prev = [  %d ], flag = [ %#0x ]\n", 
        allocator.arena, allocator.arena->next, allocator.arena->res, allocator.arena->curr, allocator.arena->prev, allocator.arena->flag);
    for (unsigned int i = 0; i < BUCKET_SMALL_CAP; i++) {
        if (allocator.bucket.small[i].arena) {
            printf("Allocator Bucket Small [ %d ] state values are: arena = [ %p ], next = [ %p ], res = [ %p ], curr = [ %d ], prev = [  %d ], flag = [ %#0x ] bucket_flag = [ %#0x ]\n", 
            i, allocator.bucket.small[i].arena, allocator.bucket.small[i].arena->next, allocator.bucket.small[i].arena->res, allocator.bucket.small[i].arena->curr, allocator.bucket.small[i].arena->prev, allocator.bucket.small[i].arena->flag, allocator.bucket.small[i].flag);
            if (allocator.bucket.small[i].blocks.table.entries) {
                printf("Entries at [ %d ] values are:\n", i);
                debug_entry_table_t(0x0, &allocator.bucket.small[i].blocks.table, i);
            }
        }
    }
    for (size_t i = 0; i < BUCKET_MEDIUM_CAP; i++) {
        if (allocator.bucket.medium[i].arena) {
            printf("Allocator Bucket Medium [ %zu ] state values are: arena = [ %p ], next = [ %p ], res = [ %p ], curr = [ %d ], prev = [  %d ], flag = [ %#0x ] bucket_flag = [ %#0x ]\n", 
            i, allocator.bucket.medium[i].arena, allocator.bucket.medium[i].arena->next, allocator.bucket.medium[i].arena->res, allocator.bucket.medium[i].arena->curr, allocator.bucket.medium[i].arena->prev, allocator.bucket.medium[i].arena->flag, allocator.bucket.medium[i].flag);
            if (allocator.bucket.medium[i].blocks.table.entries) {
                printf("Entries at [ %zu ] values are:\n", i);
                debug_entry_table_t(0x0, &allocator.bucket.medium[i].blocks.table, i);
            }
        }
    }
    for (unsigned int i = 0; i < BUCKET_LARGE_CAP; i++) {
        if (allocator.bucket.large[i].arena) {
            printf("Allocator Bucket Large [ %d ] state values are: arena = [ %p ], next = [ %p ], res = [ %p ], curr = [ %d ], prev = [  %d ], flag = [ %#0x ] bucket_flag = [ %#0x ]\n", 
            i, allocator.bucket.large[i].arena, allocator.bucket.large[i].arena->next, allocator.bucket.large[i].arena->res, allocator.bucket.large[i].arena->curr, allocator.bucket.large[i].arena->prev, allocator.bucket.large[i].arena->flag, allocator.bucket.large[i].flag);
            if (allocator.bucket.large[i].blocks.table.entries) {
                printf("Entries at [ %d ] values are:\n", i);
                debug_entry_table_t(0x0, &allocator.bucket.large[i].blocks.table, i);
            }
        }
    }
    printf("Printing out threading variable states\n");
    for (unsigned int i = 0; i < ALLOC_THREAD_POOL_SIZE; i++) {
        printf("Information for thread [ %d ]\n", i);
        debug_threads(allocator.pool[i]);
    }
}

/**
    * @description: A Free Function that recrusive calls itself if arena is full and moves it forward.
    * @param bytes: The requested bytes.
    * @return: Return a memory address of desired size or big enough to hold x amount of bytes.
               Otherwise, return null, and that will indicate that everything is full.
*/
[[gnu::hot]]
void* allocate(size_t bytes) {
    char* address = NULL;
    size_t idx = SIZE_MAX;
    int_fast16_t end = 0;
    bucket_t* slot = NULL;
    
    while(!atomic_load_explicit(&allocator.huge->done, memory_order_acquire)){}; 
    threads_t* thread_t_sync = find_thread_t(allocator.pool, ALLOC_THREAD_POOL_SIZE);
    if (thread_t_sync) {
        atomic_store_explicit(&allocator.huge->done, 0, memory_order_release);
        routine_metadata(thread_t_sync, 1, &allocator.huge->done);
        create_thread(thread_t_sync, thread_update_thread_pool);        
    } else update_thread_pool(allocator.pool, ALLOC_THREAD_POOL_SIZE);

    if (bytes <= BUCKET_LARGE_CAP) slot = find_free_slot(bytes);
    else {
        void* res = coalescing(bytes);
        if (res == NULL) return allocator_byte_request(bytes);
        else return res;
    }
    if (slot) {
        if (!slot->arena) {
            if (allocator.arena->curr == 1) slot->arena = allocator.arena;
            else slot->arena = init_arena_t();
        }
        if (slot->flag != 0x01) {
            if (bytes <= BUCKET_SMALL_CAP) {
                end = BUCKET_SMALL_CAP;
                address = pop_from_bucket(slot, bytes);
                if (address) { memset(address, 0, bytes); return address; }
                idx = allocator.bitmap.bitmap_test(allocator.bitmap, 0, BUCKET_SMALL_CAP);
            }
            if (bytes <= BUCKET_MEDIUM_CAP && bytes >= BUCKET_SMALL_CAP) {
                end = BUCKET_MEDIUM_CAP;
                address = pop_from_bucket(slot, bytes);
                if (address) { memset(address, 0, bytes); return address; }
                idx = allocator.bitmap.bitmap_test(allocator.bitmap, 0, BUCKET_MEDIUM_CAP);
            }
            else if (bytes <= BUCKET_LARGE_CAP && bytes >= BUCKET_MEDIUM_CAP) {
                end = BUCKET_LARGE_CAP;
                address = pop_from_bucket(slot, bytes);
                if (address) { memset(address, 0, bytes); return address; }
                idx = allocator.bitmap.bitmap_test(allocator.bitmap, 0, BUCKET_LARGE_CAP);
            }

            if (slot->arena->flag != 0x01 && idx != SIZE_MAX) {
                slot->arena = push(slot->arena, bytes);
                if (slot->arena->flag == 0x01) {
                    slot->flag = 0x01;
                    allocator.bitmap = allocator.bitmap.bitmap_set(allocator.bitmap, idx, 0, (size_t)end);
                    arena_t* full = slot->arena;
                    arena_t* fresh = init_arena_t();
                    fresh->next = full;
                    allocator.arena = fresh;
                    return allocate(bytes);
                }
                address = slot->arena->res;
                size_t offset = (uintptr_t)slot->arena->res - (uintptr_t)slot->arena->chunk;
                set(&slot->blocks.table, idx, offset, bytes, 0x01, address);
                memset(address, 0, bytes);
                return address;
            }
        }
    }
    else debug_allocator(bytes);
    return NULL;
}

/**
    * @description: A free function that determines if the following parameter that was passed into it is within a specific arena's memory region.
    * @param ptr: A memory address that can or is not apart of a arena. 
    * @return: Returns nothing if 'ptr' is not within any of the arena's memory range.   
*/
[[gnu::hot]]
FORCE_INLINE void deallocate(void* ptr) {
    if (!ptr) return;

    while(!atomic_load_explicit(&allocator.huge->done, memory_order_acquire)){}; 
    threads_t* thread_t_sync = find_thread_t(allocator.pool, ALLOC_THREAD_POOL_SIZE);
    if (thread_t_sync) {
        atomic_store_explicit(&allocator.huge->done, 0, memory_order_release);
        routine_metadata(thread_t_sync, 1, &allocator.huge->done);
        create_thread(thread_t_sync, thread_update_thread_pool);
    } else update_thread_pool(allocator.pool, ALLOC_THREAD_POOL_SIZE);

    bucket_t* slot = NULL;
    slot = find_slot(ptr);
    if (!slot) {
        if (!allocator.huge || !allocator.huge->region) return;

        const size_t size = allocator.huge->slots[allocator.huge->slot_cap - 1].capacity;
        uintptr_t p = (uintptr_t)ptr, base = (uintptr_t)allocator.huge->region;
        if (p < base || p >= base + (uintptr_t)allocator.huge->allocator_cap - 1) return;
        else if ((p - base) % size != 0) return;

        size_t idx = (size_t)((p - base) / HUGE_PAGE_SIZE);
        size_t offset = p - (uintptr_t)allocator.huge->region;

        if (idx > allocator.huge->slot_cap) return;
        offset_entries_t* onode = get_entry_t_by_offset(&allocator.huge->slots[idx].blocks.table, idx, offset, 0x01);
        if (!onode) return;
        else if (allocator.huge->slots[idx].space > (onode->offset + onode->bytes->bytes)) {
            allocator.huge->slots[idx].space -= (onode->offset + onode->bytes->bytes);
            entry_table_t* table =  &allocator.huge->slots[idx].blocks.table;
            if (table->entries[idx] && table->entries[idx]->next == NULL) {
                allocator.huge->slots[idx].space = 0;
                destroy(&allocator.huge->slots[idx].blocks.table, idx, onode->offset, onode->bytes->bytes);
                table_free_pages(table);
            } else {
                threads_t* t1 = find_thread_t(allocator.pool, ALLOC_THREAD_POOL_SIZE);
                if (!t1) update(&allocator.huge->slots[idx].blocks.table, idx, onode->offset, onode->bytes->bytes, 0x0);
                else {
                    unsigned char inuse = 0x0;
                    routine_metadata(t1, 6, &allocator.huge->slots[idx].blocks.table, &idx, &onode->offset, &onode->bytes->bytes, &inuse, &allocator.huge->done);
                    create_thread(t1, thread_update);
                }
            }
        } else debug_entry_table_t(0x0, &allocator.huge->slots[idx].blocks.table, idx);
        return;
    }

    unsigned char* base = (unsigned char*)slot->arena->chunk;
    if ((unsigned char*)ptr < base || (unsigned char*)ptr >= base + ARENA_SIZE) {
        #if LOGGING == 1 || LOGGING == 0
            char* res = write_long_cstr(0x01, 4, ANSI_RED, "ERROR ALLOCATOR.C: deallocate — ptr %p out of arena bounds\n", ANSI_RESET, ptr);
            const int line = __LINE__;
            #if LOGGING == 0
                printer.add(5, __FILE__, line, "FMI");
                printer.print(__FILE__, line);
            #else 
                logger.add(5, __FILE__, line, "FMI");
            #endif
            reset_and_free_cstr(1, res);
        #else 
            return;
        #endif
    }

    const atomic_size_t offset = (size_t)((uintptr_t)ptr - (uintptr_t)slot->arena->chunk);
    const atomic_size_t index = find_bucket_index(slot);
    offset_entries_t* offset_entry = get_entry_t_by_offset(&slot->blocks.table, atomic_load_explicit(&index, memory_order_relaxed), atomic_load_explicit(&offset, memory_order_relaxed), 0x01);
    
    if (offset_entry) {
        const size_t bytes = offset_entry->bytes->bytes;
        push_to_bucket(slot, offset);
        if (slot->arena && slot->arena->chunk) memset(ptr, 0xFF, bytes);

        while(!atomic_load_explicit(&allocator.huge->done, memory_order_acquire)){}
        threads_t* t1 = find_thread_t(allocator.pool, ALLOC_THREAD_POOL_SIZE);
        
        if (!t1) __rewind(slot);
        else {
            atomic_store_explicit(&allocator.huge->done, 0, memory_order_release);
            routine_metadata(t1, 2, slot, &allocator.huge->done);
            create_thread(t1, thread_rewind);  
        }
    } else {
        while(!atomic_load_explicit(&allocator.huge->done, memory_order_acquire)){}
        threads_t* t1 = find_thread_t(allocator.pool, ALLOC_THREAD_POOL_SIZE);
        if (!t1) update_block_t_by_offset(&slot->blocks, atomic_load_explicit(&index, memory_order_relaxed), atomic_load_explicit(&offset, memory_order_relaxed), 0x01);
        else {
            atomic_store_explicit(&allocator.huge->done, 0, memory_order_release);
            routine_metadata(t1, 5, &slot->blocks,
                (void*)(uintptr_t)atomic_load_explicit(&index, memory_order_relaxed),
                (void*)(uintptr_t)atomic_load_explicit(&offset, memory_order_relaxed),
                (void*)(uintptr_t)0x01,
                &allocator.huge->done);
            create_thread(t1, thread_update_block_t_by_offset);
        }
    }
}

[[gnu::cold]]
void init_allocator_t() {
    #if BENCHMARK_ENV == 1
        init_benchmark_allocator_t();
    #endif
    if (!allocator.bitmap.bits)  {
        init_logger_t();
        init_bitmap_t(&allocator.bitmap, BITMAP_SIZE);
        allocator_init_arena_t();
        allocator_init_buckets_t();
        allocator.huge = aligned_alloc(alignof(huge_block_allocator_t), sizeof(huge_block_allocator_t));
        memset(allocator.huge, 0, sizeof(huge_block_allocator_t));
        allocator_init_threads_t();
        if (!allocator.huge) return;
        init_huge_allocator();
    }

    if (!allocator.allocate) {
        allocator.allocate   = allocate;
        allocator.deallocate = deallocate;
    }
}

#if BENCHMARK_ENV == 1
    FORCE_INLINE void init_benchmark_allocator_t() {
        /* Entry functions */
        benchmark_allocator.get_entry_t_by_bytes     = get_entry_t_by_bytes;
        benchmark_allocator.get_entry_t_by_offset    = get_entry_t_by_offset;
        benchmark_allocator.update                   = update;
        benchmark_allocator.destroy                  = destroy;
        benchmark_allocator.clean                    = clean;

        /* Block functions */
        benchmark_allocator.is_mergeable             = is_mergeable;
        benchmark_allocator.merge                    = merge;
        benchmark_allocator.update_block_t_by_offset = update_block_t_by_offset;
        benchmark_allocator.get_block_t_by_offset    = get_block_t_by_offset;
        benchmark_allocator.block_t_dctor            = block_t_dctor;

        /* Coalescing */
        benchmark_allocator.coalescing               = coalescing;

        /* Bucket functions */
        benchmark_allocator.find_slot                = find_slot;
        benchmark_allocator.push_to_bucket           = push_to_bucket;
        benchmark_allocator.pop_from_bucket          = pop_from_bucket;
        benchmark_allocator.bucket_t_dctor           = bucket_t_dctor;
        benchmark_allocator.__rewind                 = __rewind;

    }
#endif

/**
    * @description: Free function that will refuse if this single allocation would eat more than half of currently-free RAM. 
    * @param bytes: The requested amount of bytes 
    * @return returns 0x01 if successful, otherwise, 0x0
*/
FORCE_INLINE unsigned char overcommit(const size_t bytes) {
    struct sysinfo info;
    if (sysinfo(&info) != 0) return 0x0;
    unsigned long available = (unsigned long)info.freeram * (unsigned long)info.mem_unit;
    return (bytes < available / 2) ? 0x1 : 0x0;
}

FORCE_INLINE void allocator_huge_resize_slots(huge_slot_t* slot, const size_t size) {
    if (!slot) return;

    void* old_ptr = slot;
    size_t old = slot->capacity;
    slot = size < ALLOC_THRESHOLD ? realloc(slot, old) : remap_address(slot, old, size);
    if (!slot) return;

    memset(slot, 1, size);
    memset(slot, size, offsetof(huge_slot_t, capacity) * size);
    memcpy(slot, old_ptr, old);
    size < ALLOC_THRESHOLD ? free(old_ptr) : munmap_address(old_ptr, old);
    allocator.huge->slot_cap = size;
}

FORCE_INLINE void* allocator_huge_update_slot(huge_slot_t* slot, const size_t index, const size_t end, size_t bytes) {
    char* address = NULL;
    uintptr_t raw = (uintptr_t)allocator.huge->region + (uintptr_t)(slot->space == 0 ? 1 : slot->space);
    uintptr_t offset = alignment(raw, bytes);
    offset -= (uintptr_t)allocator.huge->region;
    if (slot->space < slot->capacity) {
        slot->space = bytes + offset;
        address = allocator.huge->region + offset;
        set(&slot->blocks.table, index, slot->space, bytes, 0x01, address);
        return address;
    }
    else {
        allocator.huge->bitmap = allocator.huge->bitmap.bitmap_set(allocator.huge->bitmap, index, 0, end);
        return allocate(bytes);
    }
}

FORCE_INLINE void allocator_huge_update_slots(const size_t start, const size_t end) {
    for (size_t i = start; i < end; i++) { 
        allocator.huge->slots[i].space = 1;
        allocator.huge->slots[i].capacity = MAX_HUGE_SLOTS;
    }
}

[[gnu::cold]]
FORCE_INLINE void init_huge_allocator(void) {
    init_bitmap_t(&allocator.huge->bitmap, BITMAP_SIZE);
    allocator.huge->region = ENABLE_SHARED_MEMORY == 1 ? shared_address(NULL, (size_t)MAX_HUGE_SLOTS * HUGE_PAGE_SIZE, PROT_WRITE | PROT_READ,  MAP_HUGETLB | ((size_t)__builtin_ctzll(HUGE_PAGE_SIZE) << 26) | MAP_NORESERVE, -1, 0)  : private_address(NULL, (size_t)MAX_HUGE_SLOTS * HUGE_PAGE_SIZE,PROT_WRITE | PROT_READ,  MAP_HUGETLB | ((size_t)__builtin_ctzll(HUGE_PAGE_SIZE) << 26) | MAP_NORESERVE, -1, 0);
    if (allocator.huge->region == MAP_FAILED) { allocator.huge->region = NULL; return; }
    
    while(!atomic_load_explicit(&allocator.huge->done, memory_order_acquire)){}
    allocator.huge->allocator_cap = (size_t)MAX_HUGE_SLOTS * HUGE_PAGE_SIZE;
    
    allocator.huge->slots = ENABLE_SHARED_MEMORY == 1 ? 
        shared_address(NULL, (size_t)MAX_HUGE_SLOTS * sizeof(huge_slot_t), PROT_WRITE | PROT_READ, MAP_NORESERVE, -1, 0) : 
        private_address(NULL, (size_t)MAX_HUGE_SLOTS * sizeof(huge_slot_t), PROT_WRITE | PROT_READ,   MAP_NORESERVE, -1, 0);
    
    if (allocator.huge->slots == MAP_FAILED) { 
        munmap_address(allocator.huge->region, (size_t)MAX_HUGE_SLOTS * HUGE_PAGE_SIZE); 
        allocator.huge->region = NULL;
        allocator.huge->slots = NULL; 
        return; 
    } else {
        int res = madvise(allocator.huge->slots, (size_t)MAX_HUGE_SLOTS * sizeof(huge_slot_t), MADV_SEQUENTIAL | MADV_MERGEABLE);
        if (res == -1) {
            munmap_address(allocator.huge->region, (size_t)MAX_HUGE_SLOTS * HUGE_PAGE_SIZE);
            if (allocator.huge->slots) munmap_address(allocator.huge->slots, (size_t)MAX_HUGE_SLOTS * sizeof(huge_slot_t));
            allocator.huge->region = NULL;
            allocator.huge->slots = NULL;
            return;
        }
    }

    memset(allocator.huge->slots, 0, (size_t)MAX_HUGE_SLOTS * sizeof(huge_slot_t));
    atomic_store_explicit(&allocator.huge->done, 0, memory_order_release);
    threads_t* t1 = find_thread_t(allocator.pool, ALLOC_THREAD_POOL_SIZE);
    if (!t1) allocator_huge_update_slots(0, MAX_HUGE_SLOTS);
    else {
        static size_t begin = 0, end = MAX_HUGE_SLOTS;
        routine_metadata(t1, 3, &begin, &end, &allocator.huge->done);
        create_thread(t1, thread_allocator_huge_update_slots);
    }
    allocator.huge->slot_cap = (size_t)MAX_HUGE_SLOTS * sizeof(huge_slot_t);
}

[[gnu::cold]]
[[gnu::destructor]]
FORCE_INLINE void allocator_dctor() {
    
    while(!atomic_load_explicit(&allocator.huge->done, memory_order_acquire)){}
    for (size_t i = 0;  i < ALLOC_THREAD_POOL_SIZE; i++) clean_threads(&allocator.pool[i]);
    munmap_address(allocator.pool, ALLOC_THREAD_POOL_SIZE * sizeof(threads_t));
    allocator.pool = NULL;

    bucket_t_dctor();
    if (allocator.arena) {
        //if (allocator.arena->chunk) munmap_address(allocator.arena->chunk, ARENA_SIZE);
        munmap_address(allocator.arena, sizeof(arena_t));
    }
    clean_bitmap(&allocator.bitmap);
    if (allocator.huge) {
        clean_bitmap(&allocator.huge->bitmap);
        
        munmap_address(allocator.huge->region, allocator.huge->allocator_cap);
        allocator.huge->region = NULL;
        
        if (allocator.huge->slots) {
            /*for (size_t i = 0; i < allocator.huge->slot_cap; i++) {
                if (allocator.huge->slots[i].blocks.chain && allocator.huge->slots[i].blocks.chain[0]) {
                    block_t_dctor(&allocator.huge->slots[i].blocks);
                    allocator.huge->slots[i].blocks.chain = NULL;
                }
            }*/
            munmap_address(allocator.huge->slots, allocator.huge->slot_cap);
        }
        memset(allocator.huge, 0, sizeof(huge_block_allocator_t));
        if (allocator.huge) free(allocator.huge);
        allocator.huge = NULL;
    }   
}